<?php
/**
 * RefundsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.12.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TheLogicStudio\GrailPay\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use TheLogicStudio\GrailPay\ApiException;
use TheLogicStudio\GrailPay\Configuration;
use TheLogicStudio\GrailPay\FormDataProcessor;
use TheLogicStudio\GrailPay\HeaderSelector;
use TheLogicStudio\GrailPay\ObjectSerializer;

/**
 * RefundsApi Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RefundsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getBatchRefunds' => [
            'application/json',
        ],
        'getBatchRefundsByBatchRefundUuid' => [
            'application/json',
        ],
        'getRefundsByRefundUuid' => [
            'application/json',
        ],
        'getTransactionsByTransactionUuidRefunds' => [
            'application/json',
        ],
        'postTransactionsByUuidRefund' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getBatchRefunds
     *
     * Get All Batch Refunds ( STABLE )
     *
     * @param  \DateTime|null $start_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  \DateTime|null $end_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  string|null $sort_order Sorting order: &#39;oldest&#39; for ascending, &#39;newest&#39; for descending. (optional)
     * @param  int|null $page Page number for pagination. (optional)
     * @param  int|null $per_page Number of items per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefunds'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\BatchRefundListResponse|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response
     */
    public function getBatchRefunds($start_date = null, $end_date = null, $sort_order = null, $page = null, $per_page = null, string $contentType = self::contentTypes['getBatchRefunds'][0])
    {
        list($response) = $this->getBatchRefundsWithHttpInfo($start_date, $end_date, $sort_order, $page, $per_page, $contentType);
        return $response;
    }

    /**
     * Operation getBatchRefundsWithHttpInfo
     *
     * Get All Batch Refunds ( STABLE )
     *
     * @param  \DateTime|null $start_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  \DateTime|null $end_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  string|null $sort_order Sorting order: &#39;oldest&#39; for ascending, &#39;newest&#39; for descending. (optional)
     * @param  int|null $page Page number for pagination. (optional)
     * @param  int|null $per_page Number of items per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefunds'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\BatchRefundListResponse|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBatchRefundsWithHttpInfo($start_date = null, $end_date = null, $sort_order = null, $page = null, $per_page = null, string $contentType = self::contentTypes['getBatchRefunds'][0])
    {
        $request = $this->getBatchRefundsRequest($start_date, $end_date, $sort_order, $page, $per_page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\BatchRefundListResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\BatchRefundListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\BatchRefundListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getBatchRefundsAsync
     *
     * Get All Batch Refunds ( STABLE )
     *
     * @param  \DateTime|null $start_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  \DateTime|null $end_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  string|null $sort_order Sorting order: &#39;oldest&#39; for ascending, &#39;newest&#39; for descending. (optional)
     * @param  int|null $page Page number for pagination. (optional)
     * @param  int|null $per_page Number of items per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefunds'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBatchRefundsAsync($start_date = null, $end_date = null, $sort_order = null, $page = null, $per_page = null, string $contentType = self::contentTypes['getBatchRefunds'][0])
    {
        return $this->getBatchRefundsAsyncWithHttpInfo($start_date, $end_date, $sort_order, $page, $per_page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBatchRefundsAsyncWithHttpInfo
     *
     * Get All Batch Refunds ( STABLE )
     *
     * @param  \DateTime|null $start_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  \DateTime|null $end_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  string|null $sort_order Sorting order: &#39;oldest&#39; for ascending, &#39;newest&#39; for descending. (optional)
     * @param  int|null $page Page number for pagination. (optional)
     * @param  int|null $per_page Number of items per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefunds'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBatchRefundsAsyncWithHttpInfo($start_date = null, $end_date = null, $sort_order = null, $page = null, $per_page = null, string $contentType = self::contentTypes['getBatchRefunds'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\BatchRefundListResponse';
        $request = $this->getBatchRefundsRequest($start_date, $end_date, $sort_order, $page, $per_page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBatchRefunds'
     *
     * @param  \DateTime|null $start_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  \DateTime|null $end_date This parameter will filter the user&#39;s records based on the creation date of the batch refund.Date format: Y-m-d (optional)
     * @param  string|null $sort_order Sorting order: &#39;oldest&#39; for ascending, &#39;newest&#39; for descending. (optional)
     * @param  int|null $page Page number for pagination. (optional)
     * @param  int|null $per_page Number of items per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefunds'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBatchRefundsRequest($start_date = null, $end_date = null, $sort_order = null, $page = null, $per_page = null, string $contentType = self::contentTypes['getBatchRefunds'][0])
    {







        $resourcePath = '/3p/api/v2/batch-refunds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_date,
            'start_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_date,
            'end_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_order,
            'sort_order', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBatchRefundsByBatchRefundUuid
     *
     * Get Batch Refund ( STABLE )
     *
     * @param  string $batch_refund_uuid UUID of the batch refund (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefundsByBatchRefundUuid'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\GetBatchRefundsByBatchRefundUuid200Response|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response|\TheLogicStudio\GrailPay\Model\Error403ForbiddenResponse|\TheLogicStudio\GrailPay\Model\BatchRefundNotFound
     */
    public function getBatchRefundsByBatchRefundUuid($batch_refund_uuid, string $contentType = self::contentTypes['getBatchRefundsByBatchRefundUuid'][0])
    {
        list($response) = $this->getBatchRefundsByBatchRefundUuidWithHttpInfo($batch_refund_uuid, $contentType);
        return $response;
    }

    /**
     * Operation getBatchRefundsByBatchRefundUuidWithHttpInfo
     *
     * Get Batch Refund ( STABLE )
     *
     * @param  string $batch_refund_uuid UUID of the batch refund (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefundsByBatchRefundUuid'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\GetBatchRefundsByBatchRefundUuid200Response|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response|\TheLogicStudio\GrailPay\Model\Error403ForbiddenResponse|\TheLogicStudio\GrailPay\Model\BatchRefundNotFound, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBatchRefundsByBatchRefundUuidWithHttpInfo($batch_refund_uuid, string $contentType = self::contentTypes['getBatchRefundsByBatchRefundUuid'][0])
    {
        $request = $this->getBatchRefundsByBatchRefundUuidRequest($batch_refund_uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBatchRefundsByBatchRefundUuid200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\Error403ForbiddenResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\BatchRefundNotFound',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\GetBatchRefundsByBatchRefundUuid200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBatchRefundsByBatchRefundUuid200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\Error403ForbiddenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\BatchRefundNotFound',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getBatchRefundsByBatchRefundUuidAsync
     *
     * Get Batch Refund ( STABLE )
     *
     * @param  string $batch_refund_uuid UUID of the batch refund (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefundsByBatchRefundUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBatchRefundsByBatchRefundUuidAsync($batch_refund_uuid, string $contentType = self::contentTypes['getBatchRefundsByBatchRefundUuid'][0])
    {
        return $this->getBatchRefundsByBatchRefundUuidAsyncWithHttpInfo($batch_refund_uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBatchRefundsByBatchRefundUuidAsyncWithHttpInfo
     *
     * Get Batch Refund ( STABLE )
     *
     * @param  string $batch_refund_uuid UUID of the batch refund (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefundsByBatchRefundUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBatchRefundsByBatchRefundUuidAsyncWithHttpInfo($batch_refund_uuid, string $contentType = self::contentTypes['getBatchRefundsByBatchRefundUuid'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\GetBatchRefundsByBatchRefundUuid200Response';
        $request = $this->getBatchRefundsByBatchRefundUuidRequest($batch_refund_uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBatchRefundsByBatchRefundUuid'
     *
     * @param  string $batch_refund_uuid UUID of the batch refund (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBatchRefundsByBatchRefundUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBatchRefundsByBatchRefundUuidRequest($batch_refund_uuid, string $contentType = self::contentTypes['getBatchRefundsByBatchRefundUuid'][0])
    {

        // verify the required parameter 'batch_refund_uuid' is set
        if ($batch_refund_uuid === null || (is_array($batch_refund_uuid) && count($batch_refund_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $batch_refund_uuid when calling getBatchRefundsByBatchRefundUuid'
            );
        }


        $resourcePath = '/3p/api/v2/batch-refunds/{batch_refund_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($batch_refund_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'batch_refund_uuid' . '}',
                ObjectSerializer::toPathValue($batch_refund_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRefundsByRefundUuid
     *
     * Get Refund Details ( Refunds )
     *
     * @param  string $refund_uuid Refund UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefundsByRefundUuid'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid200Response|\TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid404Response|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response
     */
    public function getRefundsByRefundUuid($refund_uuid, string $contentType = self::contentTypes['getRefundsByRefundUuid'][0])
    {
        list($response) = $this->getRefundsByRefundUuidWithHttpInfo($refund_uuid, $contentType);
        return $response;
    }

    /**
     * Operation getRefundsByRefundUuidWithHttpInfo
     *
     * Get Refund Details ( Refunds )
     *
     * @param  string $refund_uuid Refund UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefundsByRefundUuid'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid200Response|\TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid404Response|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRefundsByRefundUuidWithHttpInfo($refund_uuid, string $contentType = self::contentTypes['getRefundsByRefundUuid'][0])
    {
        $request = $this->getRefundsByRefundUuidRequest($refund_uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid404Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getRefundsByRefundUuidAsync
     *
     * Get Refund Details ( Refunds )
     *
     * @param  string $refund_uuid Refund UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefundsByRefundUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRefundsByRefundUuidAsync($refund_uuid, string $contentType = self::contentTypes['getRefundsByRefundUuid'][0])
    {
        return $this->getRefundsByRefundUuidAsyncWithHttpInfo($refund_uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRefundsByRefundUuidAsyncWithHttpInfo
     *
     * Get Refund Details ( Refunds )
     *
     * @param  string $refund_uuid Refund UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefundsByRefundUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRefundsByRefundUuidAsyncWithHttpInfo($refund_uuid, string $contentType = self::contentTypes['getRefundsByRefundUuid'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\GetRefundsByRefundUuid200Response';
        $request = $this->getRefundsByRefundUuidRequest($refund_uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRefundsByRefundUuid'
     *
     * @param  string $refund_uuid Refund UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRefundsByRefundUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRefundsByRefundUuidRequest($refund_uuid, string $contentType = self::contentTypes['getRefundsByRefundUuid'][0])
    {

        // verify the required parameter 'refund_uuid' is set
        if ($refund_uuid === null || (is_array($refund_uuid) && count($refund_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $refund_uuid when calling getRefundsByRefundUuid'
            );
        }


        $resourcePath = '/3p/api/v1/refunds/{refund_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($refund_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'refund_uuid' . '}',
                ObjectSerializer::toPathValue($refund_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTransactionsByTransactionUuidRefunds
     *
     * Get Transaction Refunds ( STABLE )
     *
     * @param  string $transaction_uuid Transaction UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsByTransactionUuidRefunds'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\RefundListResponse|\TheLogicStudio\GrailPay\Model\GetTransactionsByTransactionUuidRefunds404Response|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response
     */
    public function getTransactionsByTransactionUuidRefunds($transaction_uuid, string $contentType = self::contentTypes['getTransactionsByTransactionUuidRefunds'][0])
    {
        list($response) = $this->getTransactionsByTransactionUuidRefundsWithHttpInfo($transaction_uuid, $contentType);
        return $response;
    }

    /**
     * Operation getTransactionsByTransactionUuidRefundsWithHttpInfo
     *
     * Get Transaction Refunds ( STABLE )
     *
     * @param  string $transaction_uuid Transaction UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsByTransactionUuidRefunds'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\RefundListResponse|\TheLogicStudio\GrailPay\Model\GetTransactionsByTransactionUuidRefunds404Response|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTransactionsByTransactionUuidRefundsWithHttpInfo($transaction_uuid, string $contentType = self::contentTypes['getTransactionsByTransactionUuidRefunds'][0])
    {
        $request = $this->getTransactionsByTransactionUuidRefundsRequest($transaction_uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\RefundListResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetTransactionsByTransactionUuidRefunds404Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\RefundListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\RefundListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetTransactionsByTransactionUuidRefunds404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTransactionsByTransactionUuidRefundsAsync
     *
     * Get Transaction Refunds ( STABLE )
     *
     * @param  string $transaction_uuid Transaction UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsByTransactionUuidRefunds'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionsByTransactionUuidRefundsAsync($transaction_uuid, string $contentType = self::contentTypes['getTransactionsByTransactionUuidRefunds'][0])
    {
        return $this->getTransactionsByTransactionUuidRefundsAsyncWithHttpInfo($transaction_uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTransactionsByTransactionUuidRefundsAsyncWithHttpInfo
     *
     * Get Transaction Refunds ( STABLE )
     *
     * @param  string $transaction_uuid Transaction UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsByTransactionUuidRefunds'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionsByTransactionUuidRefundsAsyncWithHttpInfo($transaction_uuid, string $contentType = self::contentTypes['getTransactionsByTransactionUuidRefunds'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\RefundListResponse';
        $request = $this->getTransactionsByTransactionUuidRefundsRequest($transaction_uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTransactionsByTransactionUuidRefunds'
     *
     * @param  string $transaction_uuid Transaction UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsByTransactionUuidRefunds'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTransactionsByTransactionUuidRefundsRequest($transaction_uuid, string $contentType = self::contentTypes['getTransactionsByTransactionUuidRefunds'][0])
    {

        // verify the required parameter 'transaction_uuid' is set
        if ($transaction_uuid === null || (is_array($transaction_uuid) && count($transaction_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $transaction_uuid when calling getTransactionsByTransactionUuidRefunds'
            );
        }


        $resourcePath = '/3p/api/v1/transactions/{transaction_uuid}/refunds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($transaction_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'transaction_uuid' . '}',
                ObjectSerializer::toPathValue($transaction_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postTransactionsByUuidRefund
     *
     * Refund a transaction ( STABLE )
     *
     * @param  string $uuid UUID of the transaction to refund (required)
     * @param  \TheLogicStudio\GrailPay\Model\V1RefundTransactionRequest $v1_refund_transaction_request v1_refund_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postTransactionsByUuidRefund'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund201Response|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response|\TheLogicStudio\GrailPay\Model\Error403ForbiddenResponse|\TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund404Response
     */
    public function postTransactionsByUuidRefund($uuid, $v1_refund_transaction_request, string $contentType = self::contentTypes['postTransactionsByUuidRefund'][0])
    {
        list($response) = $this->postTransactionsByUuidRefundWithHttpInfo($uuid, $v1_refund_transaction_request, $contentType);
        return $response;
    }

    /**
     * Operation postTransactionsByUuidRefundWithHttpInfo
     *
     * Refund a transaction ( STABLE )
     *
     * @param  string $uuid UUID of the transaction to refund (required)
     * @param  \TheLogicStudio\GrailPay\Model\V1RefundTransactionRequest $v1_refund_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postTransactionsByUuidRefund'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund201Response|\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response|\TheLogicStudio\GrailPay\Model\Error403ForbiddenResponse|\TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function postTransactionsByUuidRefundWithHttpInfo($uuid, $v1_refund_transaction_request, string $contentType = self::contentTypes['postTransactionsByUuidRefund'][0])
    {
        $request = $this->postTransactionsByUuidRefundRequest($uuid, $v1_refund_transaction_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund201Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\Error403ForbiddenResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund404Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostBankAccountsValidate401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\Error403ForbiddenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postTransactionsByUuidRefundAsync
     *
     * Refund a transaction ( STABLE )
     *
     * @param  string $uuid UUID of the transaction to refund (required)
     * @param  \TheLogicStudio\GrailPay\Model\V1RefundTransactionRequest $v1_refund_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postTransactionsByUuidRefund'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postTransactionsByUuidRefundAsync($uuid, $v1_refund_transaction_request, string $contentType = self::contentTypes['postTransactionsByUuidRefund'][0])
    {
        return $this->postTransactionsByUuidRefundAsyncWithHttpInfo($uuid, $v1_refund_transaction_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postTransactionsByUuidRefundAsyncWithHttpInfo
     *
     * Refund a transaction ( STABLE )
     *
     * @param  string $uuid UUID of the transaction to refund (required)
     * @param  \TheLogicStudio\GrailPay\Model\V1RefundTransactionRequest $v1_refund_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postTransactionsByUuidRefund'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postTransactionsByUuidRefundAsyncWithHttpInfo($uuid, $v1_refund_transaction_request, string $contentType = self::contentTypes['postTransactionsByUuidRefund'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\PostTransactionsByUuidRefund201Response';
        $request = $this->postTransactionsByUuidRefundRequest($uuid, $v1_refund_transaction_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postTransactionsByUuidRefund'
     *
     * @param  string $uuid UUID of the transaction to refund (required)
     * @param  \TheLogicStudio\GrailPay\Model\V1RefundTransactionRequest $v1_refund_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postTransactionsByUuidRefund'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postTransactionsByUuidRefundRequest($uuid, $v1_refund_transaction_request, string $contentType = self::contentTypes['postTransactionsByUuidRefund'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling postTransactionsByUuidRefund'
            );
        }

        // verify the required parameter 'v1_refund_transaction_request' is set
        if ($v1_refund_transaction_request === null || (is_array($v1_refund_transaction_request) && count($v1_refund_transaction_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $v1_refund_transaction_request when calling postTransactionsByUuidRefund'
            );
        }


        $resourcePath = '/3p/api/v1/transactions/{uuid}/refund';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($v1_refund_transaction_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($v1_refund_transaction_request));
            } else {
                $httpBody = $v1_refund_transaction_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
