<?php
/**
 * WebhooksApi
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API v3
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2026.9.30.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TheLogicStudio\GrailPay\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use TheLogicStudio\GrailPay\ApiException;
use TheLogicStudio\GrailPay\Configuration;
use TheLogicStudio\GrailPay\FormDataProcessor;
use TheLogicStudio\GrailPay\HeaderSelector;
use TheLogicStudio\GrailPay\ObjectSerializer;

/**
 * WebhooksApi Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhooksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'deleteWebhooksByUuid' => [
            'application/json',
        ],
        'getWebhooks' => [
            'application/json',
        ],
        'getWebhooksByUuid' => [
            'application/json',
        ],
        'postWebhooks' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteWebhooksByUuid
     *
     * Delete Webhook
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\DeleteWebhooksByUuid200Response|\TheLogicStudio\GrailPay\Model\V3ErrorInvalidAcceptHeader400|\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response|\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response|\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid404Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response
     */
    public function deleteWebhooksByUuid($uuid, string $contentType = self::contentTypes['deleteWebhooksByUuid'][0])
    {
        list($response) = $this->deleteWebhooksByUuidWithHttpInfo($uuid, $contentType);
        return $response;
    }

    /**
     * Operation deleteWebhooksByUuidWithHttpInfo
     *
     * Delete Webhook
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\DeleteWebhooksByUuid200Response|\TheLogicStudio\GrailPay\Model\V3ErrorInvalidAcceptHeader400|\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response|\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response|\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid404Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteWebhooksByUuidWithHttpInfo($uuid, string $contentType = self::contentTypes['deleteWebhooksByUuid'][0])
    {
        $request = $this->deleteWebhooksByUuidRequest($uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\DeleteWebhooksByUuid200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\V3ErrorInvalidAcceptHeader400',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid404Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\DeleteWebhooksByUuid200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\DeleteWebhooksByUuid200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\V3ErrorInvalidAcceptHeader400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteWebhooksByUuidAsync
     *
     * Delete Webhook
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteWebhooksByUuidAsync($uuid, string $contentType = self::contentTypes['deleteWebhooksByUuid'][0])
    {
        return $this->deleteWebhooksByUuidAsyncWithHttpInfo($uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteWebhooksByUuidAsyncWithHttpInfo
     *
     * Delete Webhook
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteWebhooksByUuidAsyncWithHttpInfo($uuid, string $contentType = self::contentTypes['deleteWebhooksByUuid'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\DeleteWebhooksByUuid200Response';
        $request = $this->deleteWebhooksByUuidRequest($uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteWebhooksByUuid'
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteWebhooksByUuidRequest($uuid, string $contentType = self::contentTypes['deleteWebhooksByUuid'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling deleteWebhooksByUuid'
            );
        }


        $resourcePath = '/api/v3/webhooks/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getWebhooks
     *
     * Get All Webhooks
     *
     * @param  bool|null $filter_is_active Filter by whether the registration is active (optional)
     * @param  string|null $filter_url Filter by URL (case-insensitive partial match) (optional)
     * @param  string|null $sort Sort by created_at. Prefix with &#39;-&#39; for descending order (the default) (optional)
     * @param  int|null $page Page number for pagination (optional)
     * @param  int|null $per_page Number of records per page (optional, default to 15)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooks'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\GetWebhooks200Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts400Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response|\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response|\TheLogicStudio\GrailPay\Model\GetWebhooks422Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response
     */
    public function getWebhooks($filter_is_active = null, $filter_url = null, $sort = null, $page = null, $per_page = 15, string $contentType = self::contentTypes['getWebhooks'][0])
    {
        list($response) = $this->getWebhooksWithHttpInfo($filter_is_active, $filter_url, $sort, $page, $per_page, $contentType);
        return $response;
    }

    /**
     * Operation getWebhooksWithHttpInfo
     *
     * Get All Webhooks
     *
     * @param  bool|null $filter_is_active Filter by whether the registration is active (optional)
     * @param  string|null $filter_url Filter by URL (case-insensitive partial match) (optional)
     * @param  string|null $sort Sort by created_at. Prefix with &#39;-&#39; for descending order (the default) (optional)
     * @param  int|null $page Page number for pagination (optional)
     * @param  int|null $per_page Number of records per page (optional, default to 15)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooks'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\GetWebhooks200Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts400Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response|\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response|\TheLogicStudio\GrailPay\Model\GetWebhooks422Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWebhooksWithHttpInfo($filter_is_active = null, $filter_url = null, $sort = null, $page = null, $per_page = 15, string $contentType = self::contentTypes['getWebhooks'][0])
    {
        $request = $this->getWebhooksRequest($filter_is_active, $filter_url, $sort, $page, $per_page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetWebhooks200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetWebhooks422Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\GetWebhooks200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetWebhooks200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetWebhooks422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getWebhooksAsync
     *
     * Get All Webhooks
     *
     * @param  bool|null $filter_is_active Filter by whether the registration is active (optional)
     * @param  string|null $filter_url Filter by URL (case-insensitive partial match) (optional)
     * @param  string|null $sort Sort by created_at. Prefix with &#39;-&#39; for descending order (the default) (optional)
     * @param  int|null $page Page number for pagination (optional)
     * @param  int|null $per_page Number of records per page (optional, default to 15)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWebhooksAsync($filter_is_active = null, $filter_url = null, $sort = null, $page = null, $per_page = 15, string $contentType = self::contentTypes['getWebhooks'][0])
    {
        return $this->getWebhooksAsyncWithHttpInfo($filter_is_active, $filter_url, $sort, $page, $per_page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getWebhooksAsyncWithHttpInfo
     *
     * Get All Webhooks
     *
     * @param  bool|null $filter_is_active Filter by whether the registration is active (optional)
     * @param  string|null $filter_url Filter by URL (case-insensitive partial match) (optional)
     * @param  string|null $sort Sort by created_at. Prefix with &#39;-&#39; for descending order (the default) (optional)
     * @param  int|null $page Page number for pagination (optional)
     * @param  int|null $per_page Number of records per page (optional, default to 15)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWebhooksAsyncWithHttpInfo($filter_is_active = null, $filter_url = null, $sort = null, $page = null, $per_page = 15, string $contentType = self::contentTypes['getWebhooks'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\GetWebhooks200Response';
        $request = $this->getWebhooksRequest($filter_is_active, $filter_url, $sort, $page, $per_page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getWebhooks'
     *
     * @param  bool|null $filter_is_active Filter by whether the registration is active (optional)
     * @param  string|null $filter_url Filter by URL (case-insensitive partial match) (optional)
     * @param  string|null $sort Sort by created_at. Prefix with &#39;-&#39; for descending order (the default) (optional)
     * @param  int|null $page Page number for pagination (optional)
     * @param  int|null $per_page Number of records per page (optional, default to 15)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getWebhooksRequest($filter_is_active = null, $filter_url = null, $sort = null, $page = null, $per_page = 15, string $contentType = self::contentTypes['getWebhooks'][0])
    {


        if ($filter_url !== null && strlen($filter_url) > 2048) {
            throw new \InvalidArgumentException('invalid length for "$filter_url" when calling WebhooksApi.getWebhooks, must be smaller than or equal to 2048.');
        }
        

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling WebhooksApi.getWebhooks, must be bigger than or equal to 1.');
        }
        
        if ($per_page !== null && $per_page > 200) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling WebhooksApi.getWebhooks, must be smaller than or equal to 200.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling WebhooksApi.getWebhooks, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/api/v3/webhooks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_is_active,
            'filter[is_active]', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_url,
            'filter[url]', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getWebhooksByUuid
     *
     * Get Webhook
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\GetWebhooksByUuid200Response|\TheLogicStudio\GrailPay\Model\V3ErrorInvalidAcceptHeader400|\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response|\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response|\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid404Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response
     */
    public function getWebhooksByUuid($uuid, string $contentType = self::contentTypes['getWebhooksByUuid'][0])
    {
        list($response) = $this->getWebhooksByUuidWithHttpInfo($uuid, $contentType);
        return $response;
    }

    /**
     * Operation getWebhooksByUuidWithHttpInfo
     *
     * Get Webhook
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\GetWebhooksByUuid200Response|\TheLogicStudio\GrailPay\Model\V3ErrorInvalidAcceptHeader400|\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response|\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response|\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid404Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWebhooksByUuidWithHttpInfo($uuid, string $contentType = self::contentTypes['getWebhooksByUuid'][0])
    {
        $request = $this->getWebhooksByUuidRequest($uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\V3ErrorInvalidAcceptHeader400',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid404Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\V3ErrorInvalidAcceptHeader400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccountsByUuidOwners403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getWebhooksByUuidAsync
     *
     * Get Webhook
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWebhooksByUuidAsync($uuid, string $contentType = self::contentTypes['getWebhooksByUuid'][0])
    {
        return $this->getWebhooksByUuidAsyncWithHttpInfo($uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getWebhooksByUuidAsyncWithHttpInfo
     *
     * Get Webhook
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWebhooksByUuidAsyncWithHttpInfo($uuid, string $contentType = self::contentTypes['getWebhooksByUuid'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\GetWebhooksByUuid200Response';
        $request = $this->getWebhooksByUuidRequest($uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getWebhooksByUuid'
     *
     * @param  string $uuid Webhook registration UUID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getWebhooksByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getWebhooksByUuidRequest($uuid, string $contentType = self::contentTypes['getWebhooksByUuid'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling getWebhooksByUuid'
            );
        }


        $resourcePath = '/api/v3/webhooks/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postWebhooks
     *
     * Register Webhook
     *
     * @param  \TheLogicStudio\GrailPay\Model\PostWebhooksRequest $post_webhooks_request post_webhooks_request (required)
     * @param  string|null $idempotency_key Optional idempotency key. Replaying the same key with the same request body returns the original response; a conflicting body returns 409. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postWebhooks'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \TheLogicStudio\GrailPay\Model\PostWebhooks201Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts400Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response|\TheLogicStudio\GrailPay\Model\PostWebhooks403Response|\TheLogicStudio\GrailPay\Model\V3ErrorIdempotency409|\TheLogicStudio\GrailPay\Model\PostWebhooks422Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response
     */
    public function postWebhooks($post_webhooks_request, $idempotency_key = null, string $contentType = self::contentTypes['postWebhooks'][0])
    {
        list($response) = $this->postWebhooksWithHttpInfo($post_webhooks_request, $idempotency_key, $contentType);
        return $response;
    }

    /**
     * Operation postWebhooksWithHttpInfo
     *
     * Register Webhook
     *
     * @param  \TheLogicStudio\GrailPay\Model\PostWebhooksRequest $post_webhooks_request (required)
     * @param  string|null $idempotency_key Optional idempotency key. Replaying the same key with the same request body returns the original response; a conflicting body returns 409. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postWebhooks'] to see the possible values for this operation
     *
     * @throws \TheLogicStudio\GrailPay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \TheLogicStudio\GrailPay\Model\PostWebhooks201Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts400Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response|\TheLogicStudio\GrailPay\Model\PostWebhooks403Response|\TheLogicStudio\GrailPay\Model\V3ErrorIdempotency409|\TheLogicStudio\GrailPay\Model\PostWebhooks422Response|\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function postWebhooksWithHttpInfo($post_webhooks_request, $idempotency_key = null, string $contentType = self::contentTypes['postWebhooks'][0])
    {
        $request = $this->postWebhooksRequest($post_webhooks_request, $idempotency_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostWebhooks201Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostWebhooks403Response',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\V3ErrorIdempotency409',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\PostWebhooks422Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\TheLogicStudio\GrailPay\Model\PostWebhooks201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostWebhooks201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostWebhooks403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\V3ErrorIdempotency409',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\PostWebhooks422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TheLogicStudio\GrailPay\Model\GetBankAccounts500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postWebhooksAsync
     *
     * Register Webhook
     *
     * @param  \TheLogicStudio\GrailPay\Model\PostWebhooksRequest $post_webhooks_request (required)
     * @param  string|null $idempotency_key Optional idempotency key. Replaying the same key with the same request body returns the original response; a conflicting body returns 409. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postWebhooks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postWebhooksAsync($post_webhooks_request, $idempotency_key = null, string $contentType = self::contentTypes['postWebhooks'][0])
    {
        return $this->postWebhooksAsyncWithHttpInfo($post_webhooks_request, $idempotency_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postWebhooksAsyncWithHttpInfo
     *
     * Register Webhook
     *
     * @param  \TheLogicStudio\GrailPay\Model\PostWebhooksRequest $post_webhooks_request (required)
     * @param  string|null $idempotency_key Optional idempotency key. Replaying the same key with the same request body returns the original response; a conflicting body returns 409. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postWebhooks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postWebhooksAsyncWithHttpInfo($post_webhooks_request, $idempotency_key = null, string $contentType = self::contentTypes['postWebhooks'][0])
    {
        $returnType = '\TheLogicStudio\GrailPay\Model\PostWebhooks201Response';
        $request = $this->postWebhooksRequest($post_webhooks_request, $idempotency_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postWebhooks'
     *
     * @param  \TheLogicStudio\GrailPay\Model\PostWebhooksRequest $post_webhooks_request (required)
     * @param  string|null $idempotency_key Optional idempotency key. Replaying the same key with the same request body returns the original response; a conflicting body returns 409. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postWebhooks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postWebhooksRequest($post_webhooks_request, $idempotency_key = null, string $contentType = self::contentTypes['postWebhooks'][0])
    {

        // verify the required parameter 'post_webhooks_request' is set
        if ($post_webhooks_request === null || (is_array($post_webhooks_request) && count($post_webhooks_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $post_webhooks_request when calling postWebhooks'
            );
        }



        $resourcePath = '/api/v3/webhooks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($post_webhooks_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($post_webhooks_request));
            } else {
                $httpBody = $post_webhooks_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (Token) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
