<?php
/**
 * CreateTransaction
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.12.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TheLogicStudio\GrailPay\Model;

use \ArrayAccess;
use \TheLogicStudio\GrailPay\ObjectSerializer;

/**
 * CreateTransaction Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateTransaction implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateTransaction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payer_uuid' => 'string',
        'payee_uuid' => 'string',
        'processor_mid' => 'string',
        'amount' => 'int',
        'transaction_fee' => 'int',
        'client_reference_id' => 'string',
        'payout_delay_days_min' => 'int',
        'speed' => 'string',
        'company_name' => 'string',
        'description' => 'string',
        'addenda' => 'string',
        'source_bank_account' => '\TheLogicStudio\GrailPay\Model\CreateTransactionSourceBankAccount',
        'destination_bank_account' => '\TheLogicStudio\GrailPay\Model\CreateTransactionSourceBankAccount',
        'failure_simulation' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'payer_uuid' => null,
        'payee_uuid' => null,
        'processor_mid' => null,
        'amount' => null,
        'transaction_fee' => null,
        'client_reference_id' => null,
        'payout_delay_days_min' => null,
        'speed' => null,
        'company_name' => null,
        'description' => null,
        'addenda' => null,
        'source_bank_account' => null,
        'destination_bank_account' => null,
        'failure_simulation' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'payer_uuid' => false,
        'payee_uuid' => false,
        'processor_mid' => false,
        'amount' => false,
        'transaction_fee' => false,
        'client_reference_id' => false,
        'payout_delay_days_min' => false,
        'speed' => false,
        'company_name' => false,
        'description' => false,
        'addenda' => false,
        'source_bank_account' => false,
        'destination_bank_account' => false,
        'failure_simulation' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payer_uuid' => 'payer_uuid',
        'payee_uuid' => 'payee_uuid',
        'processor_mid' => 'processor_mid',
        'amount' => 'amount',
        'transaction_fee' => 'transaction_fee',
        'client_reference_id' => 'client_reference_id',
        'payout_delay_days_min' => 'payout_delay_days_min',
        'speed' => 'speed',
        'company_name' => 'company_name',
        'description' => 'description',
        'addenda' => 'addenda',
        'source_bank_account' => 'source_bank_account',
        'destination_bank_account' => 'destination_bank_account',
        'failure_simulation' => 'failure_simulation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payer_uuid' => 'setPayerUuid',
        'payee_uuid' => 'setPayeeUuid',
        'processor_mid' => 'setProcessorMid',
        'amount' => 'setAmount',
        'transaction_fee' => 'setTransactionFee',
        'client_reference_id' => 'setClientReferenceId',
        'payout_delay_days_min' => 'setPayoutDelayDaysMin',
        'speed' => 'setSpeed',
        'company_name' => 'setCompanyName',
        'description' => 'setDescription',
        'addenda' => 'setAddenda',
        'source_bank_account' => 'setSourceBankAccount',
        'destination_bank_account' => 'setDestinationBankAccount',
        'failure_simulation' => 'setFailureSimulation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payer_uuid' => 'getPayerUuid',
        'payee_uuid' => 'getPayeeUuid',
        'processor_mid' => 'getProcessorMid',
        'amount' => 'getAmount',
        'transaction_fee' => 'getTransactionFee',
        'client_reference_id' => 'getClientReferenceId',
        'payout_delay_days_min' => 'getPayoutDelayDaysMin',
        'speed' => 'getSpeed',
        'company_name' => 'getCompanyName',
        'description' => 'getDescription',
        'addenda' => 'getAddenda',
        'source_bank_account' => 'getSourceBankAccount',
        'destination_bank_account' => 'getDestinationBankAccount',
        'failure_simulation' => 'getFailureSimulation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFailureSimulationAllowableValues()
    {
        return [
            
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('payer_uuid', $data ?? [], null);
        $this->setIfExists('payee_uuid', $data ?? [], null);
        $this->setIfExists('processor_mid', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('transaction_fee', $data ?? [], null);
        $this->setIfExists('client_reference_id', $data ?? [], null);
        $this->setIfExists('payout_delay_days_min', $data ?? [], null);
        $this->setIfExists('speed', $data ?? [], null);
        $this->setIfExists('company_name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('addenda', $data ?? [], null);
        $this->setIfExists('source_bank_account', $data ?? [], null);
        $this->setIfExists('destination_bank_account', $data ?? [], null);
        $this->setIfExists('failure_simulation', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getFailureSimulationAllowableValues();
        if (!is_null($this->container['failure_simulation']) && !in_array($this->container['failure_simulation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'failure_simulation', must be one of '%s'",
                $this->container['failure_simulation'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payer_uuid
     *
     * @return string|null
     */
    public function getPayerUuid()
    {
        return $this->container['payer_uuid'];
    }

    /**
     * Sets payer_uuid
     *
     * @param string|null $payer_uuid payer_uuid
     *
     * @return self
     */
    public function setPayerUuid($payer_uuid)
    {
        if (is_null($payer_uuid)) {
            throw new \InvalidArgumentException('non-nullable payer_uuid cannot be null');
        }
        $this->container['payer_uuid'] = $payer_uuid;

        return $this;
    }

    /**
     * Gets payee_uuid
     *
     * @return string|null
     */
    public function getPayeeUuid()
    {
        return $this->container['payee_uuid'];
    }

    /**
     * Sets payee_uuid
     *
     * @param string|null $payee_uuid payee_uuid
     *
     * @return self
     */
    public function setPayeeUuid($payee_uuid)
    {
        if (is_null($payee_uuid)) {
            throw new \InvalidArgumentException('non-nullable payee_uuid cannot be null');
        }
        $this->container['payee_uuid'] = $payee_uuid;

        return $this;
    }

    /**
     * Gets processor_mid
     *
     * @return string|null
     */
    public function getProcessorMid()
    {
        return $this->container['processor_mid'];
    }

    /**
     * Sets processor_mid
     *
     * @param string|null $processor_mid processor_mid
     *
     * @return self
     */
    public function setProcessorMid($processor_mid)
    {
        if (is_null($processor_mid)) {
            throw new \InvalidArgumentException('non-nullable processor_mid cannot be null');
        }
        $this->container['processor_mid'] = $processor_mid;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int|null $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets transaction_fee
     *
     * @return int|null
     */
    public function getTransactionFee()
    {
        return $this->container['transaction_fee'];
    }

    /**
     * Sets transaction_fee
     *
     * @param int|null $transaction_fee transaction_fee
     *
     * @return self
     */
    public function setTransactionFee($transaction_fee)
    {
        if (is_null($transaction_fee)) {
            throw new \InvalidArgumentException('non-nullable transaction_fee cannot be null');
        }
        $this->container['transaction_fee'] = $transaction_fee;

        return $this;
    }

    /**
     * Gets client_reference_id
     *
     * @return string|null
     */
    public function getClientReferenceId()
    {
        return $this->container['client_reference_id'];
    }

    /**
     * Sets client_reference_id
     *
     * @param string|null $client_reference_id client_reference_id
     *
     * @return self
     */
    public function setClientReferenceId($client_reference_id)
    {
        if (is_null($client_reference_id)) {
            throw new \InvalidArgumentException('non-nullable client_reference_id cannot be null');
        }
        $this->container['client_reference_id'] = $client_reference_id;

        return $this;
    }

    /**
     * Gets payout_delay_days_min
     *
     * @return int|null
     */
    public function getPayoutDelayDaysMin()
    {
        return $this->container['payout_delay_days_min'];
    }

    /**
     * Sets payout_delay_days_min
     *
     * @param int|null $payout_delay_days_min payout_delay_days_min
     *
     * @return self
     */
    public function setPayoutDelayDaysMin($payout_delay_days_min)
    {
        if (is_null($payout_delay_days_min)) {
            throw new \InvalidArgumentException('non-nullable payout_delay_days_min cannot be null');
        }
        $this->container['payout_delay_days_min'] = $payout_delay_days_min;

        return $this;
    }

    /**
     * Gets speed
     *
     * @return string|null
     */
    public function getSpeed()
    {
        return $this->container['speed'];
    }

    /**
     * Sets speed
     *
     * @param string|null $speed speed
     *
     * @return self
     */
    public function setSpeed($speed)
    {
        if (is_null($speed)) {
            throw new \InvalidArgumentException('non-nullable speed cannot be null');
        }
        $this->container['speed'] = $speed;

        return $this;
    }

    /**
     * Gets company_name
     *
     * @return string|null
     */
    public function getCompanyName()
    {
        return $this->container['company_name'];
    }

    /**
     * Sets company_name
     *
     * @param string|null $company_name company_name
     *
     * @return self
     */
    public function setCompanyName($company_name)
    {
        if (is_null($company_name)) {
            throw new \InvalidArgumentException('non-nullable company_name cannot be null');
        }
        $this->container['company_name'] = $company_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets addenda
     *
     * @return string|null
     */
    public function getAddenda()
    {
        return $this->container['addenda'];
    }

    /**
     * Sets addenda
     *
     * @param string|null $addenda addenda
     *
     * @return self
     */
    public function setAddenda($addenda)
    {
        if (is_null($addenda)) {
            throw new \InvalidArgumentException('non-nullable addenda cannot be null');
        }
        $this->container['addenda'] = $addenda;

        return $this;
    }

    /**
     * Gets source_bank_account
     *
     * @return \TheLogicStudio\GrailPay\Model\CreateTransactionSourceBankAccount|null
     */
    public function getSourceBankAccount()
    {
        return $this->container['source_bank_account'];
    }

    /**
     * Sets source_bank_account
     *
     * @param \TheLogicStudio\GrailPay\Model\CreateTransactionSourceBankAccount|null $source_bank_account source_bank_account
     *
     * @return self
     */
    public function setSourceBankAccount($source_bank_account)
    {
        if (is_null($source_bank_account)) {
            throw new \InvalidArgumentException('non-nullable source_bank_account cannot be null');
        }
        $this->container['source_bank_account'] = $source_bank_account;

        return $this;
    }

    /**
     * Gets destination_bank_account
     *
     * @return \TheLogicStudio\GrailPay\Model\CreateTransactionSourceBankAccount|null
     */
    public function getDestinationBankAccount()
    {
        return $this->container['destination_bank_account'];
    }

    /**
     * Sets destination_bank_account
     *
     * @param \TheLogicStudio\GrailPay\Model\CreateTransactionSourceBankAccount|null $destination_bank_account destination_bank_account
     *
     * @return self
     */
    public function setDestinationBankAccount($destination_bank_account)
    {
        if (is_null($destination_bank_account)) {
            throw new \InvalidArgumentException('non-nullable destination_bank_account cannot be null');
        }
        $this->container['destination_bank_account'] = $destination_bank_account;

        return $this;
    }

    /**
     * Gets failure_simulation
     *
     * @return int|null
     */
    public function getFailureSimulation()
    {
        return $this->container['failure_simulation'];
    }

    /**
     * Sets failure_simulation
     *
     * @param int|null $failure_simulation failure_simulation
     *
     * @return self
     */
    public function setFailureSimulation($failure_simulation)
    {
        if (is_null($failure_simulation)) {
            array_push($this->openAPINullablesSetToNull, 'failure_simulation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('failure_simulation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getFailureSimulationAllowableValues();
        if (!is_null($failure_simulation) && !in_array($failure_simulation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'failure_simulation', must be one of '%s'",
                    $failure_simulation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['failure_simulation'] = $failure_simulation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


