<?php
/**
 * GetClawbacks422ResponseErrors
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2026.7.24.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TheLogicStudio\GrailPay\Model;

use \ArrayAccess;
use \TheLogicStudio\GrailPay\ObjectSerializer;

/**
 * GetClawbacks422ResponseErrors Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetClawbacks422ResponseErrors implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getClawbacks_422_response_errors';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'filter_uuid' => 'object',
        'filter_transaction_uuid' => 'object',
        'filter_merchant_uuid' => 'object',
        'filter_payee_uuid' => 'object',
        'filter_status' => 'object',
        'filter_ach_id' => 'object',
        'filter_client_reference_id' => 'object',
        'filter_amount' => 'object',
        'filter_start_date' => 'object',
        'filter_end_date' => 'object',
        'sort' => 'object',
        'per_page' => 'object',
        'page' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'filter_uuid' => null,
        'filter_transaction_uuid' => null,
        'filter_merchant_uuid' => null,
        'filter_payee_uuid' => null,
        'filter_status' => null,
        'filter_ach_id' => null,
        'filter_client_reference_id' => null,
        'filter_amount' => null,
        'filter_start_date' => null,
        'filter_end_date' => null,
        'sort' => null,
        'per_page' => null,
        'page' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'filter_uuid' => false,
        'filter_transaction_uuid' => false,
        'filter_merchant_uuid' => false,
        'filter_payee_uuid' => false,
        'filter_status' => false,
        'filter_ach_id' => false,
        'filter_client_reference_id' => false,
        'filter_amount' => false,
        'filter_start_date' => false,
        'filter_end_date' => false,
        'sort' => false,
        'per_page' => false,
        'page' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'filter_uuid' => 'filter.uuid',
        'filter_transaction_uuid' => 'filter.transaction_uuid',
        'filter_merchant_uuid' => 'filter.merchant_uuid',
        'filter_payee_uuid' => 'filter.payee_uuid',
        'filter_status' => 'filter.status',
        'filter_ach_id' => 'filter.ach_id',
        'filter_client_reference_id' => 'filter.client_reference_id',
        'filter_amount' => 'filter.amount',
        'filter_start_date' => 'filter.start_date',
        'filter_end_date' => 'filter.end_date',
        'sort' => 'sort',
        'per_page' => 'per_page',
        'page' => 'page'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'filter_uuid' => 'setFilterUuid',
        'filter_transaction_uuid' => 'setFilterTransactionUuid',
        'filter_merchant_uuid' => 'setFilterMerchantUuid',
        'filter_payee_uuid' => 'setFilterPayeeUuid',
        'filter_status' => 'setFilterStatus',
        'filter_ach_id' => 'setFilterAchId',
        'filter_client_reference_id' => 'setFilterClientReferenceId',
        'filter_amount' => 'setFilterAmount',
        'filter_start_date' => 'setFilterStartDate',
        'filter_end_date' => 'setFilterEndDate',
        'sort' => 'setSort',
        'per_page' => 'setPerPage',
        'page' => 'setPage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'filter_uuid' => 'getFilterUuid',
        'filter_transaction_uuid' => 'getFilterTransactionUuid',
        'filter_merchant_uuid' => 'getFilterMerchantUuid',
        'filter_payee_uuid' => 'getFilterPayeeUuid',
        'filter_status' => 'getFilterStatus',
        'filter_ach_id' => 'getFilterAchId',
        'filter_client_reference_id' => 'getFilterClientReferenceId',
        'filter_amount' => 'getFilterAmount',
        'filter_start_date' => 'getFilterStartDate',
        'filter_end_date' => 'getFilterEndDate',
        'sort' => 'getSort',
        'per_page' => 'getPerPage',
        'page' => 'getPage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('filter_uuid', $data ?? [], null);
        $this->setIfExists('filter_transaction_uuid', $data ?? [], null);
        $this->setIfExists('filter_merchant_uuid', $data ?? [], null);
        $this->setIfExists('filter_payee_uuid', $data ?? [], null);
        $this->setIfExists('filter_status', $data ?? [], null);
        $this->setIfExists('filter_ach_id', $data ?? [], null);
        $this->setIfExists('filter_client_reference_id', $data ?? [], null);
        $this->setIfExists('filter_amount', $data ?? [], null);
        $this->setIfExists('filter_start_date', $data ?? [], null);
        $this->setIfExists('filter_end_date', $data ?? [], null);
        $this->setIfExists('sort', $data ?? [], null);
        $this->setIfExists('per_page', $data ?? [], null);
        $this->setIfExists('page', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets filter_uuid
     *
     * @return object|null
     */
    public function getFilterUuid()
    {
        return $this->container['filter_uuid'];
    }

    /**
     * Sets filter_uuid
     *
     * @param object|null $filter_uuid filter_uuid
     *
     * @return self
     */
    public function setFilterUuid($filter_uuid)
    {
        if (is_null($filter_uuid)) {
            throw new \InvalidArgumentException('non-nullable filter_uuid cannot be null');
        }
        $this->container['filter_uuid'] = $filter_uuid;

        return $this;
    }

    /**
     * Gets filter_transaction_uuid
     *
     * @return object|null
     */
    public function getFilterTransactionUuid()
    {
        return $this->container['filter_transaction_uuid'];
    }

    /**
     * Sets filter_transaction_uuid
     *
     * @param object|null $filter_transaction_uuid filter_transaction_uuid
     *
     * @return self
     */
    public function setFilterTransactionUuid($filter_transaction_uuid)
    {
        if (is_null($filter_transaction_uuid)) {
            throw new \InvalidArgumentException('non-nullable filter_transaction_uuid cannot be null');
        }
        $this->container['filter_transaction_uuid'] = $filter_transaction_uuid;

        return $this;
    }

    /**
     * Gets filter_merchant_uuid
     *
     * @return object|null
     */
    public function getFilterMerchantUuid()
    {
        return $this->container['filter_merchant_uuid'];
    }

    /**
     * Sets filter_merchant_uuid
     *
     * @param object|null $filter_merchant_uuid filter_merchant_uuid
     *
     * @return self
     */
    public function setFilterMerchantUuid($filter_merchant_uuid)
    {
        if (is_null($filter_merchant_uuid)) {
            throw new \InvalidArgumentException('non-nullable filter_merchant_uuid cannot be null');
        }
        $this->container['filter_merchant_uuid'] = $filter_merchant_uuid;

        return $this;
    }

    /**
     * Gets filter_payee_uuid
     *
     * @return object|null
     */
    public function getFilterPayeeUuid()
    {
        return $this->container['filter_payee_uuid'];
    }

    /**
     * Sets filter_payee_uuid
     *
     * @param object|null $filter_payee_uuid filter_payee_uuid
     *
     * @return self
     */
    public function setFilterPayeeUuid($filter_payee_uuid)
    {
        if (is_null($filter_payee_uuid)) {
            throw new \InvalidArgumentException('non-nullable filter_payee_uuid cannot be null');
        }
        $this->container['filter_payee_uuid'] = $filter_payee_uuid;

        return $this;
    }

    /**
     * Gets filter_status
     *
     * @return object|null
     */
    public function getFilterStatus()
    {
        return $this->container['filter_status'];
    }

    /**
     * Sets filter_status
     *
     * @param object|null $filter_status filter_status
     *
     * @return self
     */
    public function setFilterStatus($filter_status)
    {
        if (is_null($filter_status)) {
            throw new \InvalidArgumentException('non-nullable filter_status cannot be null');
        }
        $this->container['filter_status'] = $filter_status;

        return $this;
    }

    /**
     * Gets filter_ach_id
     *
     * @return object|null
     */
    public function getFilterAchId()
    {
        return $this->container['filter_ach_id'];
    }

    /**
     * Sets filter_ach_id
     *
     * @param object|null $filter_ach_id filter_ach_id
     *
     * @return self
     */
    public function setFilterAchId($filter_ach_id)
    {
        if (is_null($filter_ach_id)) {
            throw new \InvalidArgumentException('non-nullable filter_ach_id cannot be null');
        }
        $this->container['filter_ach_id'] = $filter_ach_id;

        return $this;
    }

    /**
     * Gets filter_client_reference_id
     *
     * @return object|null
     */
    public function getFilterClientReferenceId()
    {
        return $this->container['filter_client_reference_id'];
    }

    /**
     * Sets filter_client_reference_id
     *
     * @param object|null $filter_client_reference_id filter_client_reference_id
     *
     * @return self
     */
    public function setFilterClientReferenceId($filter_client_reference_id)
    {
        if (is_null($filter_client_reference_id)) {
            throw new \InvalidArgumentException('non-nullable filter_client_reference_id cannot be null');
        }
        $this->container['filter_client_reference_id'] = $filter_client_reference_id;

        return $this;
    }

    /**
     * Gets filter_amount
     *
     * @return object|null
     */
    public function getFilterAmount()
    {
        return $this->container['filter_amount'];
    }

    /**
     * Sets filter_amount
     *
     * @param object|null $filter_amount filter_amount
     *
     * @return self
     */
    public function setFilterAmount($filter_amount)
    {
        if (is_null($filter_amount)) {
            throw new \InvalidArgumentException('non-nullable filter_amount cannot be null');
        }
        $this->container['filter_amount'] = $filter_amount;

        return $this;
    }

    /**
     * Gets filter_start_date
     *
     * @return object|null
     */
    public function getFilterStartDate()
    {
        return $this->container['filter_start_date'];
    }

    /**
     * Sets filter_start_date
     *
     * @param object|null $filter_start_date filter_start_date
     *
     * @return self
     */
    public function setFilterStartDate($filter_start_date)
    {
        if (is_null($filter_start_date)) {
            throw new \InvalidArgumentException('non-nullable filter_start_date cannot be null');
        }
        $this->container['filter_start_date'] = $filter_start_date;

        return $this;
    }

    /**
     * Gets filter_end_date
     *
     * @return object|null
     */
    public function getFilterEndDate()
    {
        return $this->container['filter_end_date'];
    }

    /**
     * Sets filter_end_date
     *
     * @param object|null $filter_end_date filter_end_date
     *
     * @return self
     */
    public function setFilterEndDate($filter_end_date)
    {
        if (is_null($filter_end_date)) {
            throw new \InvalidArgumentException('non-nullable filter_end_date cannot be null');
        }
        $this->container['filter_end_date'] = $filter_end_date;

        return $this;
    }

    /**
     * Gets sort
     *
     * @return object|null
     */
    public function getSort()
    {
        return $this->container['sort'];
    }

    /**
     * Sets sort
     *
     * @param object|null $sort sort
     *
     * @return self
     */
    public function setSort($sort)
    {
        if (is_null($sort)) {
            throw new \InvalidArgumentException('non-nullable sort cannot be null');
        }
        $this->container['sort'] = $sort;

        return $this;
    }

    /**
     * Gets per_page
     *
     * @return object|null
     */
    public function getPerPage()
    {
        return $this->container['per_page'];
    }

    /**
     * Sets per_page
     *
     * @param object|null $per_page per_page
     *
     * @return self
     */
    public function setPerPage($per_page)
    {
        if (is_null($per_page)) {
            throw new \InvalidArgumentException('non-nullable per_page cannot be null');
        }
        $this->container['per_page'] = $per_page;

        return $this;
    }

    /**
     * Gets page
     *
     * @return object|null
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param object|null $page page
     *
     * @return self
     */
    public function setPage($page)
    {
        if (is_null($page)) {
            throw new \InvalidArgumentException('non-nullable page cannot be null');
        }
        $this->container['page'] = $page;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


