<?php
/**
 * V3BeneficialOwnerValidationError
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.11.10.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TheLogicStudio\GrailPay\Model;

use \ArrayAccess;
use \TheLogicStudio\GrailPay\ObjectSerializer;

/**
 * V3BeneficialOwnerValidationError Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V3BeneficialOwnerValidationError implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'V3BeneficialOwnerValidationError';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'beneficial_owners' => 'object',
        'beneficial_owners_0_first_name' => 'object',
        'beneficial_owners_0_last_name' => 'object',
        'beneficial_owners_0_dob' => 'object',
        'beneficial_owners_0_ssn9' => 'object',
        'beneficial_owners_0_is_beneficial_owner' => 'object',
        'beneficial_owners_0_is_director' => 'object',
        'beneficial_owners_0_is_significant_control_person' => 'object',
        'beneficial_owners_0_ownership_percentage' => 'object',
        'beneficial_owners_0_email' => 'object',
        'beneficial_owners_0_phone' => 'object',
        'beneficial_owners_0_occupation' => 'object',
        'beneficial_owners_0_address' => 'object',
        'beneficial_owners_0_address_line_1' => 'object',
        'beneficial_owners_0_address_line_2' => 'object',
        'beneficial_owners_0_address_city' => 'object',
        'beneficial_owners_0_address_state' => 'object',
        'beneficial_owners_0_address_zip' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'beneficial_owners' => null,
        'beneficial_owners_0_first_name' => null,
        'beneficial_owners_0_last_name' => null,
        'beneficial_owners_0_dob' => null,
        'beneficial_owners_0_ssn9' => null,
        'beneficial_owners_0_is_beneficial_owner' => null,
        'beneficial_owners_0_is_director' => null,
        'beneficial_owners_0_is_significant_control_person' => null,
        'beneficial_owners_0_ownership_percentage' => null,
        'beneficial_owners_0_email' => null,
        'beneficial_owners_0_phone' => null,
        'beneficial_owners_0_occupation' => null,
        'beneficial_owners_0_address' => null,
        'beneficial_owners_0_address_line_1' => null,
        'beneficial_owners_0_address_line_2' => null,
        'beneficial_owners_0_address_city' => null,
        'beneficial_owners_0_address_state' => null,
        'beneficial_owners_0_address_zip' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'beneficial_owners' => false,
        'beneficial_owners_0_first_name' => false,
        'beneficial_owners_0_last_name' => false,
        'beneficial_owners_0_dob' => false,
        'beneficial_owners_0_ssn9' => false,
        'beneficial_owners_0_is_beneficial_owner' => false,
        'beneficial_owners_0_is_director' => false,
        'beneficial_owners_0_is_significant_control_person' => false,
        'beneficial_owners_0_ownership_percentage' => false,
        'beneficial_owners_0_email' => false,
        'beneficial_owners_0_phone' => false,
        'beneficial_owners_0_occupation' => false,
        'beneficial_owners_0_address' => false,
        'beneficial_owners_0_address_line_1' => false,
        'beneficial_owners_0_address_line_2' => false,
        'beneficial_owners_0_address_city' => false,
        'beneficial_owners_0_address_state' => false,
        'beneficial_owners_0_address_zip' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'beneficial_owners' => 'beneficial_owners',
        'beneficial_owners_0_first_name' => 'beneficial_owners.0.first_name',
        'beneficial_owners_0_last_name' => 'beneficial_owners.0.last_name',
        'beneficial_owners_0_dob' => 'beneficial_owners.0.dob',
        'beneficial_owners_0_ssn9' => 'beneficial_owners.0.ssn9',
        'beneficial_owners_0_is_beneficial_owner' => 'beneficial_owners.0.is_beneficial_owner',
        'beneficial_owners_0_is_director' => 'beneficial_owners.0.is_director',
        'beneficial_owners_0_is_significant_control_person' => 'beneficial_owners.0.is_significant_control_person',
        'beneficial_owners_0_ownership_percentage' => 'beneficial_owners.0.ownership_percentage',
        'beneficial_owners_0_email' => 'beneficial_owners.0.email',
        'beneficial_owners_0_phone' => 'beneficial_owners.0.phone',
        'beneficial_owners_0_occupation' => 'beneficial_owners.0.occupation',
        'beneficial_owners_0_address' => 'beneficial_owners.0.address',
        'beneficial_owners_0_address_line_1' => 'beneficial_owners.0.address.line_1',
        'beneficial_owners_0_address_line_2' => 'beneficial_owners.0.address.line_2',
        'beneficial_owners_0_address_city' => 'beneficial_owners.0.address.city',
        'beneficial_owners_0_address_state' => 'beneficial_owners.0.address.state',
        'beneficial_owners_0_address_zip' => 'beneficial_owners.0.address.zip'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'beneficial_owners' => 'setBeneficialOwners',
        'beneficial_owners_0_first_name' => 'setBeneficialOwners0FirstName',
        'beneficial_owners_0_last_name' => 'setBeneficialOwners0LastName',
        'beneficial_owners_0_dob' => 'setBeneficialOwners0Dob',
        'beneficial_owners_0_ssn9' => 'setBeneficialOwners0Ssn9',
        'beneficial_owners_0_is_beneficial_owner' => 'setBeneficialOwners0IsBeneficialOwner',
        'beneficial_owners_0_is_director' => 'setBeneficialOwners0IsDirector',
        'beneficial_owners_0_is_significant_control_person' => 'setBeneficialOwners0IsSignificantControlPerson',
        'beneficial_owners_0_ownership_percentage' => 'setBeneficialOwners0OwnershipPercentage',
        'beneficial_owners_0_email' => 'setBeneficialOwners0Email',
        'beneficial_owners_0_phone' => 'setBeneficialOwners0Phone',
        'beneficial_owners_0_occupation' => 'setBeneficialOwners0Occupation',
        'beneficial_owners_0_address' => 'setBeneficialOwners0Address',
        'beneficial_owners_0_address_line_1' => 'setBeneficialOwners0AddressLine1',
        'beneficial_owners_0_address_line_2' => 'setBeneficialOwners0AddressLine2',
        'beneficial_owners_0_address_city' => 'setBeneficialOwners0AddressCity',
        'beneficial_owners_0_address_state' => 'setBeneficialOwners0AddressState',
        'beneficial_owners_0_address_zip' => 'setBeneficialOwners0AddressZip'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'beneficial_owners' => 'getBeneficialOwners',
        'beneficial_owners_0_first_name' => 'getBeneficialOwners0FirstName',
        'beneficial_owners_0_last_name' => 'getBeneficialOwners0LastName',
        'beneficial_owners_0_dob' => 'getBeneficialOwners0Dob',
        'beneficial_owners_0_ssn9' => 'getBeneficialOwners0Ssn9',
        'beneficial_owners_0_is_beneficial_owner' => 'getBeneficialOwners0IsBeneficialOwner',
        'beneficial_owners_0_is_director' => 'getBeneficialOwners0IsDirector',
        'beneficial_owners_0_is_significant_control_person' => 'getBeneficialOwners0IsSignificantControlPerson',
        'beneficial_owners_0_ownership_percentage' => 'getBeneficialOwners0OwnershipPercentage',
        'beneficial_owners_0_email' => 'getBeneficialOwners0Email',
        'beneficial_owners_0_phone' => 'getBeneficialOwners0Phone',
        'beneficial_owners_0_occupation' => 'getBeneficialOwners0Occupation',
        'beneficial_owners_0_address' => 'getBeneficialOwners0Address',
        'beneficial_owners_0_address_line_1' => 'getBeneficialOwners0AddressLine1',
        'beneficial_owners_0_address_line_2' => 'getBeneficialOwners0AddressLine2',
        'beneficial_owners_0_address_city' => 'getBeneficialOwners0AddressCity',
        'beneficial_owners_0_address_state' => 'getBeneficialOwners0AddressState',
        'beneficial_owners_0_address_zip' => 'getBeneficialOwners0AddressZip'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('beneficial_owners', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_first_name', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_last_name', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_dob', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_ssn9', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_is_beneficial_owner', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_is_director', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_is_significant_control_person', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_ownership_percentage', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_email', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_phone', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_occupation', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_address', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_address_line_1', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_address_line_2', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_address_city', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_address_state', $data ?? [], null);
        $this->setIfExists('beneficial_owners_0_address_zip', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets beneficial_owners
     *
     * @return object|null
     */
    public function getBeneficialOwners()
    {
        return $this->container['beneficial_owners'];
    }

    /**
     * Sets beneficial_owners
     *
     * @param object|null $beneficial_owners beneficial_owners
     *
     * @return self
     */
    public function setBeneficialOwners($beneficial_owners)
    {
        if (is_null($beneficial_owners)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners cannot be null');
        }
        $this->container['beneficial_owners'] = $beneficial_owners;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_first_name
     *
     * @return object|null
     */
    public function getBeneficialOwners0FirstName()
    {
        return $this->container['beneficial_owners_0_first_name'];
    }

    /**
     * Sets beneficial_owners_0_first_name
     *
     * @param object|null $beneficial_owners_0_first_name beneficial_owners_0_first_name
     *
     * @return self
     */
    public function setBeneficialOwners0FirstName($beneficial_owners_0_first_name)
    {
        if (is_null($beneficial_owners_0_first_name)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_first_name cannot be null');
        }
        $this->container['beneficial_owners_0_first_name'] = $beneficial_owners_0_first_name;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_last_name
     *
     * @return object|null
     */
    public function getBeneficialOwners0LastName()
    {
        return $this->container['beneficial_owners_0_last_name'];
    }

    /**
     * Sets beneficial_owners_0_last_name
     *
     * @param object|null $beneficial_owners_0_last_name beneficial_owners_0_last_name
     *
     * @return self
     */
    public function setBeneficialOwners0LastName($beneficial_owners_0_last_name)
    {
        if (is_null($beneficial_owners_0_last_name)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_last_name cannot be null');
        }
        $this->container['beneficial_owners_0_last_name'] = $beneficial_owners_0_last_name;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_dob
     *
     * @return object|null
     */
    public function getBeneficialOwners0Dob()
    {
        return $this->container['beneficial_owners_0_dob'];
    }

    /**
     * Sets beneficial_owners_0_dob
     *
     * @param object|null $beneficial_owners_0_dob beneficial_owners_0_dob
     *
     * @return self
     */
    public function setBeneficialOwners0Dob($beneficial_owners_0_dob)
    {
        if (is_null($beneficial_owners_0_dob)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_dob cannot be null');
        }
        $this->container['beneficial_owners_0_dob'] = $beneficial_owners_0_dob;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_ssn9
     *
     * @return object|null
     */
    public function getBeneficialOwners0Ssn9()
    {
        return $this->container['beneficial_owners_0_ssn9'];
    }

    /**
     * Sets beneficial_owners_0_ssn9
     *
     * @param object|null $beneficial_owners_0_ssn9 beneficial_owners_0_ssn9
     *
     * @return self
     */
    public function setBeneficialOwners0Ssn9($beneficial_owners_0_ssn9)
    {
        if (is_null($beneficial_owners_0_ssn9)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_ssn9 cannot be null');
        }
        $this->container['beneficial_owners_0_ssn9'] = $beneficial_owners_0_ssn9;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_is_beneficial_owner
     *
     * @return object|null
     */
    public function getBeneficialOwners0IsBeneficialOwner()
    {
        return $this->container['beneficial_owners_0_is_beneficial_owner'];
    }

    /**
     * Sets beneficial_owners_0_is_beneficial_owner
     *
     * @param object|null $beneficial_owners_0_is_beneficial_owner beneficial_owners_0_is_beneficial_owner
     *
     * @return self
     */
    public function setBeneficialOwners0IsBeneficialOwner($beneficial_owners_0_is_beneficial_owner)
    {
        if (is_null($beneficial_owners_0_is_beneficial_owner)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_is_beneficial_owner cannot be null');
        }
        $this->container['beneficial_owners_0_is_beneficial_owner'] = $beneficial_owners_0_is_beneficial_owner;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_is_director
     *
     * @return object|null
     */
    public function getBeneficialOwners0IsDirector()
    {
        return $this->container['beneficial_owners_0_is_director'];
    }

    /**
     * Sets beneficial_owners_0_is_director
     *
     * @param object|null $beneficial_owners_0_is_director beneficial_owners_0_is_director
     *
     * @return self
     */
    public function setBeneficialOwners0IsDirector($beneficial_owners_0_is_director)
    {
        if (is_null($beneficial_owners_0_is_director)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_is_director cannot be null');
        }
        $this->container['beneficial_owners_0_is_director'] = $beneficial_owners_0_is_director;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_is_significant_control_person
     *
     * @return object|null
     */
    public function getBeneficialOwners0IsSignificantControlPerson()
    {
        return $this->container['beneficial_owners_0_is_significant_control_person'];
    }

    /**
     * Sets beneficial_owners_0_is_significant_control_person
     *
     * @param object|null $beneficial_owners_0_is_significant_control_person beneficial_owners_0_is_significant_control_person
     *
     * @return self
     */
    public function setBeneficialOwners0IsSignificantControlPerson($beneficial_owners_0_is_significant_control_person)
    {
        if (is_null($beneficial_owners_0_is_significant_control_person)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_is_significant_control_person cannot be null');
        }
        $this->container['beneficial_owners_0_is_significant_control_person'] = $beneficial_owners_0_is_significant_control_person;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_ownership_percentage
     *
     * @return object|null
     */
    public function getBeneficialOwners0OwnershipPercentage()
    {
        return $this->container['beneficial_owners_0_ownership_percentage'];
    }

    /**
     * Sets beneficial_owners_0_ownership_percentage
     *
     * @param object|null $beneficial_owners_0_ownership_percentage beneficial_owners_0_ownership_percentage
     *
     * @return self
     */
    public function setBeneficialOwners0OwnershipPercentage($beneficial_owners_0_ownership_percentage)
    {
        if (is_null($beneficial_owners_0_ownership_percentage)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_ownership_percentage cannot be null');
        }
        $this->container['beneficial_owners_0_ownership_percentage'] = $beneficial_owners_0_ownership_percentage;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_email
     *
     * @return object|null
     */
    public function getBeneficialOwners0Email()
    {
        return $this->container['beneficial_owners_0_email'];
    }

    /**
     * Sets beneficial_owners_0_email
     *
     * @param object|null $beneficial_owners_0_email beneficial_owners_0_email
     *
     * @return self
     */
    public function setBeneficialOwners0Email($beneficial_owners_0_email)
    {
        if (is_null($beneficial_owners_0_email)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_email cannot be null');
        }
        $this->container['beneficial_owners_0_email'] = $beneficial_owners_0_email;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_phone
     *
     * @return object|null
     */
    public function getBeneficialOwners0Phone()
    {
        return $this->container['beneficial_owners_0_phone'];
    }

    /**
     * Sets beneficial_owners_0_phone
     *
     * @param object|null $beneficial_owners_0_phone beneficial_owners_0_phone
     *
     * @return self
     */
    public function setBeneficialOwners0Phone($beneficial_owners_0_phone)
    {
        if (is_null($beneficial_owners_0_phone)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_phone cannot be null');
        }
        $this->container['beneficial_owners_0_phone'] = $beneficial_owners_0_phone;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_occupation
     *
     * @return object|null
     */
    public function getBeneficialOwners0Occupation()
    {
        return $this->container['beneficial_owners_0_occupation'];
    }

    /**
     * Sets beneficial_owners_0_occupation
     *
     * @param object|null $beneficial_owners_0_occupation beneficial_owners_0_occupation
     *
     * @return self
     */
    public function setBeneficialOwners0Occupation($beneficial_owners_0_occupation)
    {
        if (is_null($beneficial_owners_0_occupation)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_occupation cannot be null');
        }
        $this->container['beneficial_owners_0_occupation'] = $beneficial_owners_0_occupation;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_address
     *
     * @return object|null
     */
    public function getBeneficialOwners0Address()
    {
        return $this->container['beneficial_owners_0_address'];
    }

    /**
     * Sets beneficial_owners_0_address
     *
     * @param object|null $beneficial_owners_0_address beneficial_owners_0_address
     *
     * @return self
     */
    public function setBeneficialOwners0Address($beneficial_owners_0_address)
    {
        if (is_null($beneficial_owners_0_address)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_address cannot be null');
        }
        $this->container['beneficial_owners_0_address'] = $beneficial_owners_0_address;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_address_line_1
     *
     * @return object|null
     */
    public function getBeneficialOwners0AddressLine1()
    {
        return $this->container['beneficial_owners_0_address_line_1'];
    }

    /**
     * Sets beneficial_owners_0_address_line_1
     *
     * @param object|null $beneficial_owners_0_address_line_1 beneficial_owners_0_address_line_1
     *
     * @return self
     */
    public function setBeneficialOwners0AddressLine1($beneficial_owners_0_address_line_1)
    {
        if (is_null($beneficial_owners_0_address_line_1)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_address_line_1 cannot be null');
        }
        $this->container['beneficial_owners_0_address_line_1'] = $beneficial_owners_0_address_line_1;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_address_line_2
     *
     * @return object|null
     */
    public function getBeneficialOwners0AddressLine2()
    {
        return $this->container['beneficial_owners_0_address_line_2'];
    }

    /**
     * Sets beneficial_owners_0_address_line_2
     *
     * @param object|null $beneficial_owners_0_address_line_2 beneficial_owners_0_address_line_2
     *
     * @return self
     */
    public function setBeneficialOwners0AddressLine2($beneficial_owners_0_address_line_2)
    {
        if (is_null($beneficial_owners_0_address_line_2)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_address_line_2 cannot be null');
        }
        $this->container['beneficial_owners_0_address_line_2'] = $beneficial_owners_0_address_line_2;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_address_city
     *
     * @return object|null
     */
    public function getBeneficialOwners0AddressCity()
    {
        return $this->container['beneficial_owners_0_address_city'];
    }

    /**
     * Sets beneficial_owners_0_address_city
     *
     * @param object|null $beneficial_owners_0_address_city beneficial_owners_0_address_city
     *
     * @return self
     */
    public function setBeneficialOwners0AddressCity($beneficial_owners_0_address_city)
    {
        if (is_null($beneficial_owners_0_address_city)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_address_city cannot be null');
        }
        $this->container['beneficial_owners_0_address_city'] = $beneficial_owners_0_address_city;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_address_state
     *
     * @return object|null
     */
    public function getBeneficialOwners0AddressState()
    {
        return $this->container['beneficial_owners_0_address_state'];
    }

    /**
     * Sets beneficial_owners_0_address_state
     *
     * @param object|null $beneficial_owners_0_address_state beneficial_owners_0_address_state
     *
     * @return self
     */
    public function setBeneficialOwners0AddressState($beneficial_owners_0_address_state)
    {
        if (is_null($beneficial_owners_0_address_state)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_address_state cannot be null');
        }
        $this->container['beneficial_owners_0_address_state'] = $beneficial_owners_0_address_state;

        return $this;
    }

    /**
     * Gets beneficial_owners_0_address_zip
     *
     * @return object|null
     */
    public function getBeneficialOwners0AddressZip()
    {
        return $this->container['beneficial_owners_0_address_zip'];
    }

    /**
     * Sets beneficial_owners_0_address_zip
     *
     * @param object|null $beneficial_owners_0_address_zip beneficial_owners_0_address_zip
     *
     * @return self
     */
    public function setBeneficialOwners0AddressZip($beneficial_owners_0_address_zip)
    {
        if (is_null($beneficial_owners_0_address_zip)) {
            throw new \InvalidArgumentException('non-nullable beneficial_owners_0_address_zip cannot be null');
        }
        $this->container['beneficial_owners_0_address_zip'] = $beneficial_owners_0_address_zip;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


