<?php
/**
 * V3MerchantValidationError
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.11.10.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TheLogicStudio\GrailPay\Model;

use \ArrayAccess;
use \TheLogicStudio\GrailPay\ObjectSerializer;

/**
 * V3MerchantValidationError Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V3MerchantValidationError implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'V3MerchantValidationError';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'merchant_name' => 'object',
        'merchant_tin' => 'object',
        'merchant_trading_name' => 'object',
        'merchant_entity_type' => 'object',
        'merchant_incorporation_date' => 'object',
        'merchant_incorporation_state' => 'object',
        'merchant_transaction_fee_percent' => 'object',
        'merchant_transaction_fee_fixed' => 'object',
        'merchant_maximum_transaction_fee' => 'object',
        'merchant_address_type' => 'object',
        'merchant_address' => 'object',
        'merchant_address_line_1' => 'object',
        'merchant_address_line_2' => 'object',
        'merchant_address_city' => 'object',
        'merchant_address_state' => 'object',
        'merchant_address_zip' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'merchant_name' => null,
        'merchant_tin' => null,
        'merchant_trading_name' => null,
        'merchant_entity_type' => null,
        'merchant_incorporation_date' => null,
        'merchant_incorporation_state' => null,
        'merchant_transaction_fee_percent' => null,
        'merchant_transaction_fee_fixed' => null,
        'merchant_maximum_transaction_fee' => null,
        'merchant_address_type' => null,
        'merchant_address' => null,
        'merchant_address_line_1' => null,
        'merchant_address_line_2' => null,
        'merchant_address_city' => null,
        'merchant_address_state' => null,
        'merchant_address_zip' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'merchant_name' => false,
        'merchant_tin' => false,
        'merchant_trading_name' => false,
        'merchant_entity_type' => false,
        'merchant_incorporation_date' => false,
        'merchant_incorporation_state' => false,
        'merchant_transaction_fee_percent' => false,
        'merchant_transaction_fee_fixed' => false,
        'merchant_maximum_transaction_fee' => false,
        'merchant_address_type' => false,
        'merchant_address' => false,
        'merchant_address_line_1' => false,
        'merchant_address_line_2' => false,
        'merchant_address_city' => false,
        'merchant_address_state' => false,
        'merchant_address_zip' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'merchant_name' => 'merchant.name',
        'merchant_tin' => 'merchant.tin',
        'merchant_trading_name' => 'merchant.trading_name',
        'merchant_entity_type' => 'merchant.entity_type',
        'merchant_incorporation_date' => 'merchant.incorporation_date',
        'merchant_incorporation_state' => 'merchant.incorporation_state',
        'merchant_transaction_fee_percent' => 'merchant.transaction_fee_percent',
        'merchant_transaction_fee_fixed' => 'merchant.transaction_fee_fixed',
        'merchant_maximum_transaction_fee' => 'merchant.maximum_transaction_fee',
        'merchant_address_type' => 'merchant.address_type',
        'merchant_address' => 'merchant.address',
        'merchant_address_line_1' => 'merchant.address.line_1',
        'merchant_address_line_2' => 'merchant.address.line_2',
        'merchant_address_city' => 'merchant.address.city',
        'merchant_address_state' => 'merchant.address.state',
        'merchant_address_zip' => 'merchant.address.zip'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'merchant_name' => 'setMerchantName',
        'merchant_tin' => 'setMerchantTin',
        'merchant_trading_name' => 'setMerchantTradingName',
        'merchant_entity_type' => 'setMerchantEntityType',
        'merchant_incorporation_date' => 'setMerchantIncorporationDate',
        'merchant_incorporation_state' => 'setMerchantIncorporationState',
        'merchant_transaction_fee_percent' => 'setMerchantTransactionFeePercent',
        'merchant_transaction_fee_fixed' => 'setMerchantTransactionFeeFixed',
        'merchant_maximum_transaction_fee' => 'setMerchantMaximumTransactionFee',
        'merchant_address_type' => 'setMerchantAddressType',
        'merchant_address' => 'setMerchantAddress',
        'merchant_address_line_1' => 'setMerchantAddressLine1',
        'merchant_address_line_2' => 'setMerchantAddressLine2',
        'merchant_address_city' => 'setMerchantAddressCity',
        'merchant_address_state' => 'setMerchantAddressState',
        'merchant_address_zip' => 'setMerchantAddressZip'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'merchant_name' => 'getMerchantName',
        'merchant_tin' => 'getMerchantTin',
        'merchant_trading_name' => 'getMerchantTradingName',
        'merchant_entity_type' => 'getMerchantEntityType',
        'merchant_incorporation_date' => 'getMerchantIncorporationDate',
        'merchant_incorporation_state' => 'getMerchantIncorporationState',
        'merchant_transaction_fee_percent' => 'getMerchantTransactionFeePercent',
        'merchant_transaction_fee_fixed' => 'getMerchantTransactionFeeFixed',
        'merchant_maximum_transaction_fee' => 'getMerchantMaximumTransactionFee',
        'merchant_address_type' => 'getMerchantAddressType',
        'merchant_address' => 'getMerchantAddress',
        'merchant_address_line_1' => 'getMerchantAddressLine1',
        'merchant_address_line_2' => 'getMerchantAddressLine2',
        'merchant_address_city' => 'getMerchantAddressCity',
        'merchant_address_state' => 'getMerchantAddressState',
        'merchant_address_zip' => 'getMerchantAddressZip'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('merchant_name', $data ?? [], null);
        $this->setIfExists('merchant_tin', $data ?? [], null);
        $this->setIfExists('merchant_trading_name', $data ?? [], null);
        $this->setIfExists('merchant_entity_type', $data ?? [], null);
        $this->setIfExists('merchant_incorporation_date', $data ?? [], null);
        $this->setIfExists('merchant_incorporation_state', $data ?? [], null);
        $this->setIfExists('merchant_transaction_fee_percent', $data ?? [], null);
        $this->setIfExists('merchant_transaction_fee_fixed', $data ?? [], null);
        $this->setIfExists('merchant_maximum_transaction_fee', $data ?? [], null);
        $this->setIfExists('merchant_address_type', $data ?? [], null);
        $this->setIfExists('merchant_address', $data ?? [], null);
        $this->setIfExists('merchant_address_line_1', $data ?? [], null);
        $this->setIfExists('merchant_address_line_2', $data ?? [], null);
        $this->setIfExists('merchant_address_city', $data ?? [], null);
        $this->setIfExists('merchant_address_state', $data ?? [], null);
        $this->setIfExists('merchant_address_zip', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets merchant_name
     *
     * @return object|null
     */
    public function getMerchantName()
    {
        return $this->container['merchant_name'];
    }

    /**
     * Sets merchant_name
     *
     * @param object|null $merchant_name merchant_name
     *
     * @return self
     */
    public function setMerchantName($merchant_name)
    {
        if (is_null($merchant_name)) {
            throw new \InvalidArgumentException('non-nullable merchant_name cannot be null');
        }
        $this->container['merchant_name'] = $merchant_name;

        return $this;
    }

    /**
     * Gets merchant_tin
     *
     * @return object|null
     */
    public function getMerchantTin()
    {
        return $this->container['merchant_tin'];
    }

    /**
     * Sets merchant_tin
     *
     * @param object|null $merchant_tin merchant_tin
     *
     * @return self
     */
    public function setMerchantTin($merchant_tin)
    {
        if (is_null($merchant_tin)) {
            throw new \InvalidArgumentException('non-nullable merchant_tin cannot be null');
        }
        $this->container['merchant_tin'] = $merchant_tin;

        return $this;
    }

    /**
     * Gets merchant_trading_name
     *
     * @return object|null
     */
    public function getMerchantTradingName()
    {
        return $this->container['merchant_trading_name'];
    }

    /**
     * Sets merchant_trading_name
     *
     * @param object|null $merchant_trading_name merchant_trading_name
     *
     * @return self
     */
    public function setMerchantTradingName($merchant_trading_name)
    {
        if (is_null($merchant_trading_name)) {
            throw new \InvalidArgumentException('non-nullable merchant_trading_name cannot be null');
        }
        $this->container['merchant_trading_name'] = $merchant_trading_name;

        return $this;
    }

    /**
     * Gets merchant_entity_type
     *
     * @return object|null
     */
    public function getMerchantEntityType()
    {
        return $this->container['merchant_entity_type'];
    }

    /**
     * Sets merchant_entity_type
     *
     * @param object|null $merchant_entity_type merchant_entity_type
     *
     * @return self
     */
    public function setMerchantEntityType($merchant_entity_type)
    {
        if (is_null($merchant_entity_type)) {
            throw new \InvalidArgumentException('non-nullable merchant_entity_type cannot be null');
        }
        $this->container['merchant_entity_type'] = $merchant_entity_type;

        return $this;
    }

    /**
     * Gets merchant_incorporation_date
     *
     * @return object|null
     */
    public function getMerchantIncorporationDate()
    {
        return $this->container['merchant_incorporation_date'];
    }

    /**
     * Sets merchant_incorporation_date
     *
     * @param object|null $merchant_incorporation_date merchant_incorporation_date
     *
     * @return self
     */
    public function setMerchantIncorporationDate($merchant_incorporation_date)
    {
        if (is_null($merchant_incorporation_date)) {
            throw new \InvalidArgumentException('non-nullable merchant_incorporation_date cannot be null');
        }
        $this->container['merchant_incorporation_date'] = $merchant_incorporation_date;

        return $this;
    }

    /**
     * Gets merchant_incorporation_state
     *
     * @return object|null
     */
    public function getMerchantIncorporationState()
    {
        return $this->container['merchant_incorporation_state'];
    }

    /**
     * Sets merchant_incorporation_state
     *
     * @param object|null $merchant_incorporation_state merchant_incorporation_state
     *
     * @return self
     */
    public function setMerchantIncorporationState($merchant_incorporation_state)
    {
        if (is_null($merchant_incorporation_state)) {
            throw new \InvalidArgumentException('non-nullable merchant_incorporation_state cannot be null');
        }
        $this->container['merchant_incorporation_state'] = $merchant_incorporation_state;

        return $this;
    }

    /**
     * Gets merchant_transaction_fee_percent
     *
     * @return object|null
     */
    public function getMerchantTransactionFeePercent()
    {
        return $this->container['merchant_transaction_fee_percent'];
    }

    /**
     * Sets merchant_transaction_fee_percent
     *
     * @param object|null $merchant_transaction_fee_percent merchant_transaction_fee_percent
     *
     * @return self
     */
    public function setMerchantTransactionFeePercent($merchant_transaction_fee_percent)
    {
        if (is_null($merchant_transaction_fee_percent)) {
            throw new \InvalidArgumentException('non-nullable merchant_transaction_fee_percent cannot be null');
        }
        $this->container['merchant_transaction_fee_percent'] = $merchant_transaction_fee_percent;

        return $this;
    }

    /**
     * Gets merchant_transaction_fee_fixed
     *
     * @return object|null
     */
    public function getMerchantTransactionFeeFixed()
    {
        return $this->container['merchant_transaction_fee_fixed'];
    }

    /**
     * Sets merchant_transaction_fee_fixed
     *
     * @param object|null $merchant_transaction_fee_fixed merchant_transaction_fee_fixed
     *
     * @return self
     */
    public function setMerchantTransactionFeeFixed($merchant_transaction_fee_fixed)
    {
        if (is_null($merchant_transaction_fee_fixed)) {
            throw new \InvalidArgumentException('non-nullable merchant_transaction_fee_fixed cannot be null');
        }
        $this->container['merchant_transaction_fee_fixed'] = $merchant_transaction_fee_fixed;

        return $this;
    }

    /**
     * Gets merchant_maximum_transaction_fee
     *
     * @return object|null
     */
    public function getMerchantMaximumTransactionFee()
    {
        return $this->container['merchant_maximum_transaction_fee'];
    }

    /**
     * Sets merchant_maximum_transaction_fee
     *
     * @param object|null $merchant_maximum_transaction_fee merchant_maximum_transaction_fee
     *
     * @return self
     */
    public function setMerchantMaximumTransactionFee($merchant_maximum_transaction_fee)
    {
        if (is_null($merchant_maximum_transaction_fee)) {
            throw new \InvalidArgumentException('non-nullable merchant_maximum_transaction_fee cannot be null');
        }
        $this->container['merchant_maximum_transaction_fee'] = $merchant_maximum_transaction_fee;

        return $this;
    }

    /**
     * Gets merchant_address_type
     *
     * @return object|null
     */
    public function getMerchantAddressType()
    {
        return $this->container['merchant_address_type'];
    }

    /**
     * Sets merchant_address_type
     *
     * @param object|null $merchant_address_type merchant_address_type
     *
     * @return self
     */
    public function setMerchantAddressType($merchant_address_type)
    {
        if (is_null($merchant_address_type)) {
            throw new \InvalidArgumentException('non-nullable merchant_address_type cannot be null');
        }
        $this->container['merchant_address_type'] = $merchant_address_type;

        return $this;
    }

    /**
     * Gets merchant_address
     *
     * @return object|null
     */
    public function getMerchantAddress()
    {
        return $this->container['merchant_address'];
    }

    /**
     * Sets merchant_address
     *
     * @param object|null $merchant_address merchant_address
     *
     * @return self
     */
    public function setMerchantAddress($merchant_address)
    {
        if (is_null($merchant_address)) {
            throw new \InvalidArgumentException('non-nullable merchant_address cannot be null');
        }
        $this->container['merchant_address'] = $merchant_address;

        return $this;
    }

    /**
     * Gets merchant_address_line_1
     *
     * @return object|null
     */
    public function getMerchantAddressLine1()
    {
        return $this->container['merchant_address_line_1'];
    }

    /**
     * Sets merchant_address_line_1
     *
     * @param object|null $merchant_address_line_1 merchant_address_line_1
     *
     * @return self
     */
    public function setMerchantAddressLine1($merchant_address_line_1)
    {
        if (is_null($merchant_address_line_1)) {
            throw new \InvalidArgumentException('non-nullable merchant_address_line_1 cannot be null');
        }
        $this->container['merchant_address_line_1'] = $merchant_address_line_1;

        return $this;
    }

    /**
     * Gets merchant_address_line_2
     *
     * @return object|null
     */
    public function getMerchantAddressLine2()
    {
        return $this->container['merchant_address_line_2'];
    }

    /**
     * Sets merchant_address_line_2
     *
     * @param object|null $merchant_address_line_2 merchant_address_line_2
     *
     * @return self
     */
    public function setMerchantAddressLine2($merchant_address_line_2)
    {
        if (is_null($merchant_address_line_2)) {
            throw new \InvalidArgumentException('non-nullable merchant_address_line_2 cannot be null');
        }
        $this->container['merchant_address_line_2'] = $merchant_address_line_2;

        return $this;
    }

    /**
     * Gets merchant_address_city
     *
     * @return object|null
     */
    public function getMerchantAddressCity()
    {
        return $this->container['merchant_address_city'];
    }

    /**
     * Sets merchant_address_city
     *
     * @param object|null $merchant_address_city merchant_address_city
     *
     * @return self
     */
    public function setMerchantAddressCity($merchant_address_city)
    {
        if (is_null($merchant_address_city)) {
            throw new \InvalidArgumentException('non-nullable merchant_address_city cannot be null');
        }
        $this->container['merchant_address_city'] = $merchant_address_city;

        return $this;
    }

    /**
     * Gets merchant_address_state
     *
     * @return object|null
     */
    public function getMerchantAddressState()
    {
        return $this->container['merchant_address_state'];
    }

    /**
     * Sets merchant_address_state
     *
     * @param object|null $merchant_address_state merchant_address_state
     *
     * @return self
     */
    public function setMerchantAddressState($merchant_address_state)
    {
        if (is_null($merchant_address_state)) {
            throw new \InvalidArgumentException('non-nullable merchant_address_state cannot be null');
        }
        $this->container['merchant_address_state'] = $merchant_address_state;

        return $this;
    }

    /**
     * Gets merchant_address_zip
     *
     * @return object|null
     */
    public function getMerchantAddressZip()
    {
        return $this->container['merchant_address_zip'];
    }

    /**
     * Sets merchant_address_zip
     *
     * @param object|null $merchant_address_zip merchant_address_zip
     *
     * @return self
     */
    public function setMerchantAddressZip($merchant_address_zip)
    {
        if (is_null($merchant_address_zip)) {
            throw new \InvalidArgumentException('non-nullable merchant_address_zip cannot be null');
        }
        $this->container['merchant_address_zip'] = $merchant_address_zip;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


