<?php
/**
 * V3PersonValidationError
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.11.10.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TheLogicStudio\GrailPay\Model;

use \ArrayAccess;
use \TheLogicStudio\GrailPay\ObjectSerializer;

/**
 * V3PersonValidationError Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V3PersonValidationError implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'V3PersonValidationError';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'person_first_name' => 'object',
        'person_last_name' => 'object',
        'person_email' => 'object',
        'person_phone' => 'object',
        'person_address_line_1' => 'object',
        'person_address_line_2' => 'object',
        'person_address_city' => 'object',
        'person_address_state' => 'object',
        'person_address_zip' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'person_first_name' => null,
        'person_last_name' => null,
        'person_email' => null,
        'person_phone' => null,
        'person_address_line_1' => null,
        'person_address_line_2' => null,
        'person_address_city' => null,
        'person_address_state' => null,
        'person_address_zip' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'person_first_name' => false,
        'person_last_name' => false,
        'person_email' => false,
        'person_phone' => false,
        'person_address_line_1' => false,
        'person_address_line_2' => false,
        'person_address_city' => false,
        'person_address_state' => false,
        'person_address_zip' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'person_first_name' => 'person.first_name',
        'person_last_name' => 'person.last_name',
        'person_email' => 'person.email',
        'person_phone' => 'person.phone',
        'person_address_line_1' => 'person.address.line_1',
        'person_address_line_2' => 'person.address.line_2',
        'person_address_city' => 'person.address.city',
        'person_address_state' => 'person.address.state',
        'person_address_zip' => 'person.address.zip'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'person_first_name' => 'setPersonFirstName',
        'person_last_name' => 'setPersonLastName',
        'person_email' => 'setPersonEmail',
        'person_phone' => 'setPersonPhone',
        'person_address_line_1' => 'setPersonAddressLine1',
        'person_address_line_2' => 'setPersonAddressLine2',
        'person_address_city' => 'setPersonAddressCity',
        'person_address_state' => 'setPersonAddressState',
        'person_address_zip' => 'setPersonAddressZip'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'person_first_name' => 'getPersonFirstName',
        'person_last_name' => 'getPersonLastName',
        'person_email' => 'getPersonEmail',
        'person_phone' => 'getPersonPhone',
        'person_address_line_1' => 'getPersonAddressLine1',
        'person_address_line_2' => 'getPersonAddressLine2',
        'person_address_city' => 'getPersonAddressCity',
        'person_address_state' => 'getPersonAddressState',
        'person_address_zip' => 'getPersonAddressZip'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('person_first_name', $data ?? [], null);
        $this->setIfExists('person_last_name', $data ?? [], null);
        $this->setIfExists('person_email', $data ?? [], null);
        $this->setIfExists('person_phone', $data ?? [], null);
        $this->setIfExists('person_address_line_1', $data ?? [], null);
        $this->setIfExists('person_address_line_2', $data ?? [], null);
        $this->setIfExists('person_address_city', $data ?? [], null);
        $this->setIfExists('person_address_state', $data ?? [], null);
        $this->setIfExists('person_address_zip', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets person_first_name
     *
     * @return object|null
     */
    public function getPersonFirstName()
    {
        return $this->container['person_first_name'];
    }

    /**
     * Sets person_first_name
     *
     * @param object|null $person_first_name person_first_name
     *
     * @return self
     */
    public function setPersonFirstName($person_first_name)
    {
        if (is_null($person_first_name)) {
            throw new \InvalidArgumentException('non-nullable person_first_name cannot be null');
        }
        $this->container['person_first_name'] = $person_first_name;

        return $this;
    }

    /**
     * Gets person_last_name
     *
     * @return object|null
     */
    public function getPersonLastName()
    {
        return $this->container['person_last_name'];
    }

    /**
     * Sets person_last_name
     *
     * @param object|null $person_last_name person_last_name
     *
     * @return self
     */
    public function setPersonLastName($person_last_name)
    {
        if (is_null($person_last_name)) {
            throw new \InvalidArgumentException('non-nullable person_last_name cannot be null');
        }
        $this->container['person_last_name'] = $person_last_name;

        return $this;
    }

    /**
     * Gets person_email
     *
     * @return object|null
     */
    public function getPersonEmail()
    {
        return $this->container['person_email'];
    }

    /**
     * Sets person_email
     *
     * @param object|null $person_email person_email
     *
     * @return self
     */
    public function setPersonEmail($person_email)
    {
        if (is_null($person_email)) {
            throw new \InvalidArgumentException('non-nullable person_email cannot be null');
        }
        $this->container['person_email'] = $person_email;

        return $this;
    }

    /**
     * Gets person_phone
     *
     * @return object|null
     */
    public function getPersonPhone()
    {
        return $this->container['person_phone'];
    }

    /**
     * Sets person_phone
     *
     * @param object|null $person_phone person_phone
     *
     * @return self
     */
    public function setPersonPhone($person_phone)
    {
        if (is_null($person_phone)) {
            throw new \InvalidArgumentException('non-nullable person_phone cannot be null');
        }
        $this->container['person_phone'] = $person_phone;

        return $this;
    }

    /**
     * Gets person_address_line_1
     *
     * @return object|null
     */
    public function getPersonAddressLine1()
    {
        return $this->container['person_address_line_1'];
    }

    /**
     * Sets person_address_line_1
     *
     * @param object|null $person_address_line_1 person_address_line_1
     *
     * @return self
     */
    public function setPersonAddressLine1($person_address_line_1)
    {
        if (is_null($person_address_line_1)) {
            throw new \InvalidArgumentException('non-nullable person_address_line_1 cannot be null');
        }
        $this->container['person_address_line_1'] = $person_address_line_1;

        return $this;
    }

    /**
     * Gets person_address_line_2
     *
     * @return object|null
     */
    public function getPersonAddressLine2()
    {
        return $this->container['person_address_line_2'];
    }

    /**
     * Sets person_address_line_2
     *
     * @param object|null $person_address_line_2 person_address_line_2
     *
     * @return self
     */
    public function setPersonAddressLine2($person_address_line_2)
    {
        if (is_null($person_address_line_2)) {
            throw new \InvalidArgumentException('non-nullable person_address_line_2 cannot be null');
        }
        $this->container['person_address_line_2'] = $person_address_line_2;

        return $this;
    }

    /**
     * Gets person_address_city
     *
     * @return object|null
     */
    public function getPersonAddressCity()
    {
        return $this->container['person_address_city'];
    }

    /**
     * Sets person_address_city
     *
     * @param object|null $person_address_city person_address_city
     *
     * @return self
     */
    public function setPersonAddressCity($person_address_city)
    {
        if (is_null($person_address_city)) {
            throw new \InvalidArgumentException('non-nullable person_address_city cannot be null');
        }
        $this->container['person_address_city'] = $person_address_city;

        return $this;
    }

    /**
     * Gets person_address_state
     *
     * @return object|null
     */
    public function getPersonAddressState()
    {
        return $this->container['person_address_state'];
    }

    /**
     * Sets person_address_state
     *
     * @param object|null $person_address_state person_address_state
     *
     * @return self
     */
    public function setPersonAddressState($person_address_state)
    {
        if (is_null($person_address_state)) {
            throw new \InvalidArgumentException('non-nullable person_address_state cannot be null');
        }
        $this->container['person_address_state'] = $person_address_state;

        return $this;
    }

    /**
     * Gets person_address_zip
     *
     * @return object|null
     */
    public function getPersonAddressZip()
    {
        return $this->container['person_address_zip'];
    }

    /**
     * Sets person_address_zip
     *
     * @param object|null $person_address_zip person_address_zip
     *
     * @return self
     */
    public function setPersonAddressZip($person_address_zip)
    {
        if (is_null($person_address_zip)) {
            throw new \InvalidArgumentException('non-nullable person_address_zip cannot be null');
        }
        $this->container['person_address_zip'] = $person_address_zip;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


