<?php
/**
 * BusinessResponseBusinessOwnersInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.12.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TheLogicStudio\GrailPay\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BusinessResponseBusinessOwnersInnerTest Class Doc Comment
 *
 * @category    Class
 * @description BusinessResponseBusinessOwnersInner
 * @package     TheLogicStudio\GrailPay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BusinessResponseBusinessOwnersInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BusinessResponseBusinessOwnersInner"
     */
    public function testBusinessResponseBusinessOwnersInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dob"
     */
    public function testPropertyDob()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ssn9"
     */
    public function testPropertySsn9()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "address_line_1"
     */
    public function testPropertyAddressLine1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_beneficial_owner"
     */
    public function testPropertyIsBeneficialOwner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_director"
     */
    public function testPropertyIsDirector()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_account_owner"
     */
    public function testPropertyIsAccountOwner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_share_holder"
     */
    public function testPropertyIsShareHolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_significant_control_person"
     */
    public function testPropertyIsSignificantControlPerson()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ownership_percentage"
     */
    public function testPropertyOwnershipPercentage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "occupation"
     */
    public function testPropertyOccupation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_transaction_completed_at"
     */
    public function testPropertyFirstTransactionCompletedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
