<?php
/**
 * PayoutResourceModalityTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API v3
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2026.9.30.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TheLogicStudio\GrailPay\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PayoutResourceModalityTest Class Doc Comment
 *
 * @category    Class
 * @description PayoutResourceModality
 * @package     TheLogicStudio\GrailPay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PayoutResourceModalityTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PayoutResourceModality"
     */
    public function testPayoutResourceModality()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_rail"
     */
    public function testPropertyPaymentRail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "speed"
     */
    public function testPropertySpeed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
