<?php
/**
 * PostPeopleByUuidBankAccounts422ResponseErrorsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.12.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TheLogicStudio\GrailPay\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostPeopleByUuidBankAccounts422ResponseErrorsTest Class Doc Comment
 *
 * @category    Class
 * @description PostPeopleByUuidBankAccounts422ResponseErrors
 * @package     TheLogicStudio\GrailPay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostPeopleByUuidBankAccounts422ResponseErrorsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostPeopleByUuidBankAccounts422ResponseErrors"
     */
    public function testPostPeopleByUuidBankAccounts422ResponseErrors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "person_first_name"
     */
    public function testPropertyPersonFirstName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "person_last_name"
     */
    public function testPropertyPersonLastName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "billing_merchant_uuid"
     */
    public function testPropertyBillingMerchantUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "billing_processor_mid"
     */
    public function testPropertyBillingProcessorMid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account"
     */
    public function testPropertyBankAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_plaid_account_id"
     */
    public function testPropertyBankAccountPlaidAccountId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_plaid_access_token"
     */
    public function testPropertyBankAccountPlaidAccessToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_account_number"
     */
    public function testPropertyBankAccountAccountNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_routing_number"
     */
    public function testPropertyBankAccountRoutingNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_account_name"
     */
    public function testPropertyBankAccountAccountName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_account_account_type"
     */
    public function testPropertyBankAccountAccountType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "actions_account_intelligence"
     */
    public function testPropertyActionsAccountIntelligence()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "actions_account_intelligence_version"
     */
    public function testPropertyActionsAccountIntelligenceVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "actions_account_intelligence_name_match"
     */
    public function testPropertyActionsAccountIntelligenceNameMatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
