<?php
/**
 * V1RegisterPersonRequestBankAccountCustomTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.12.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TheLogicStudio\GrailPay\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V1RegisterPersonRequestBankAccountCustomTest Class Doc Comment
 *
 * @category    Class
 * @description V1RegisterPersonRequestBankAccountCustom
 * @package     TheLogicStudio\GrailPay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1RegisterPersonRequestBankAccountCustomTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1RegisterPersonRequestBankAccountCustom"
     */
    public function testV1RegisterPersonRequestBankAccountCustom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "routing_number"
     */
    public function testPropertyRoutingNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_type"
     */
    public function testPropertyAccountType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "validate_account_routing"
     */
    public function testPropertyValidateAccountRouting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
