<?php
/**
 * StableApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.11.10.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TheLogicStudio\GrailPay\Test\Api;

use \TheLogicStudio\GrailPay\Configuration;
use \TheLogicStudio\GrailPay\ApiException;
use \TheLogicStudio\GrailPay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * StableApiTest Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StableApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteBankAccounts
     *
     * Delete a bank account ( STABLE ).
     *
     */
    public function testDeleteBankAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteTransactions
     *
     * Cancel a transaction ( STABLE ).
     *
     */
    public function testDeleteTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteUsers
     *
     * Deleting a User ( STABLE ).
     *
     */
    public function testDeleteUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebhook
     *
     * De-register Webhook ( STABLE ).
     *
     */
    public function testDeleteWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBankAccount
     *
     * Get bank account details ( STABLE ).
     *
     */
    public function testGetBankAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBankAccountsHistory
     *
     * Fetch the transaction history for a bank account. ( STABLE ).
     *
     */
    public function testGetBankAccountsHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBatchPayoutsBusiness
     *
     * Get Business Batch Payout ( STABLE ).
     *
     */
    public function testGetBatchPayoutsBusiness()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBatchPayoutsMerchant
     *
     * Get Merchant Batch Payout ( STABLE ).
     *
     */
    public function testGetBatchPayoutsMerchant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBatchPayoutsPerson
     *
     * Get Person Batch Payout ( STABLE ).
     *
     */
    public function testGetBatchPayoutsPerson()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBatchPayoutsProcessor
     *
     * Get Processor Batch Payout ( STABLE ).
     *
     */
    public function testGetBatchPayoutsProcessor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBatchRefunds
     *
     * Get All Batch Refunds ( STABLE ).
     *
     */
    public function testGetBatchRefunds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBusinesses
     *
     * Get All Businesses ( STABLE ).
     *
     */
    public function testGetBusinesses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMerchants
     *
     * Get All Merchants ( STABLE ).
     *
     */
    public function testGetMerchants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMerchantsBilling
     *
     * Get Billing by Merchant User UUID ( STABLE ).
     *
     */
    public function testGetMerchantsBilling()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPeople
     *
     * Get All People ( STABLE ).
     *
     */
    public function testGetPeople()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransactions
     *
     * Get Transactions ( STABLE ).
     *
     */
    public function testGetTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransactionsRefunds
     *
     * Get Transaction Refunds ( STABLE ).
     *
     */
    public function testGetTransactionsRefunds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUsersBankAccounts
     *
     * Get all bank accounts for a user ( STABLE ).
     *
     */
    public function testGetUsersBankAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUsersBankAccountsBalance
     *
     * Fetch the bank account balance ( STABLE ).
     *
     */
    public function testGetUsersBankAccountsBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebhook
     *
     * Get registered webhooks ( STABLE ).
     *
     */
    public function testGetWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchBusinesses
     *
     * Update a Business into the ACH application ( STABLE ).
     *
     */
    public function testPatchBusinesses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchMerchants
     *
     * Update a Merchant into the ACH application ( STABLE ).
     *
     */
    public function testPatchMerchants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchPeople
     *
     * Update a Person into the ACH application ( STABLE ).
     *
     */
    public function testPatchPeople()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBankAccountBalance
     *
     * Get balance approval ( STABLE ).
     *
     */
    public function testPostBankAccountBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBankAccountUser
     *
     * Get User Details by bank account ( STABLE ).
     *
     */
    public function testPostBankAccountUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBankAccountsValidate
     *
     * Validate bank account and routing number ( STABLE ).
     *
     */
    public function testPostBankAccountsValidate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBusinesses
     *
     * Onboard a new Business into the ACH application ( STABLE ).
     *
     */
    public function testPostBusinesses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postMerchants
     *
     * Onboard a new Merchant into the ACH application ( STABLE ).
     *
     */
    public function testPostMerchants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPeople
     *
     * Onboard a new Person into the ACH application ( STABLE ).
     *
     */
    public function testPostPeople()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPeopleBankAccounts
     *
     * Onboard a new Person into the ACH application ( STABLE ).
     *
     */
    public function testPostPeopleBankAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTransaction
     *
     * Create a new transaction ( STABLE ).
     *
     */
    public function testPostTransaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTransactionsRefund
     *
     * Refund a transaction ( STABLE ).
     *
     */
    public function testPostTransactionsRefund()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postWebhook
     *
     * Register Webhook ( STABLE ).
     *
     */
    public function testPostWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putBankAccountSwitchDefault
     *
     * Switch default bank account ( STABLE ).
     *
     */
    public function testPutBankAccountSwitchDefault()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
