<?php
/**
 * UsersApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GrailPay ACH API
 *
 * API Documentation for moving funds via ACH using the GrailPay ACH API
 *
 * The version of the OpenAPI document: 2025.11.10.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TheLogicStudio\GrailPay\Test\Api;

use \TheLogicStudio\GrailPay\Configuration;
use \TheLogicStudio\GrailPay\ApiException;
use \TheLogicStudio\GrailPay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\GrailPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteUsers
     *
     * Deleting a User ( STABLE ).
     *
     */
    public function testDeleteUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBusinesses
     *
     * Get All Businesses ( STABLE ).
     *
     */
    public function testGetBusinesses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMerchants
     *
     * Get All Merchants ( STABLE ).
     *
     */
    public function testGetMerchants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPeople
     *
     * Get All People ( STABLE ).
     *
     */
    public function testGetPeople()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchBusinesses
     *
     * Update a Business into the ACH application ( STABLE ).
     *
     */
    public function testPatchBusinesses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchMerchants
     *
     * Update a Merchant into the ACH application ( STABLE ).
     *
     */
    public function testPatchMerchants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchPeople
     *
     * Update a Person into the ACH application ( STABLE ).
     *
     */
    public function testPatchPeople()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBusinesses
     *
     * Onboard a new Business into the ACH application ( STABLE ).
     *
     */
    public function testPostBusinesses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postMerchants
     *
     * Onboard a new Merchant into the ACH application ( STABLE ).
     *
     */
    public function testPostMerchants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPeople
     *
     * Onboard a new Person into the ACH application ( STABLE ).
     *
     */
    public function testPostPeople()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
